### ISSUE TITLE
Activity Panel: Orders

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#144]
**Designs**: [inVision Project](https://automattic.invisionapp.com/d/main#/projects/prototypes/14683254)
**Master Thread**: [link](https://wp.me/p6riRB-3hZ)

![order-card](https://user-images.githubusercontent.com/22080/42191393-8fd9d8b6-7e17-11e8-8e0d-eaf9e2252fbe.png)

This issue will serve as a parent issue for all related components and features of the Orders Activity Panel. When all child tasks are complete, and the issue is closed, we should be able to consider this part of the activity panel _feature complete_ for the initial release of the plugin.

__Components__
The following components ( [designs here](https://automattic.invisionapp.com/d/main#/console/14683254/305328643/preview) ) need to be created ( or updated ) to match the hi fi designs:

- [x] Secondary Button #145
- [x] Primary Button #145
- [x] Borderless Button #145
- [x] Flag #146
- [x] Gravatar #147
- [x] Order Status #148
- [x] Card
- [x] Popover
- [x] Popover Mobile Styling #151
- [ ] Print Menu* #150 

__States__
- [x] Loading: Mobile / Non #155
- [x] Collapsed: Mobile / Non #156
- [ ] Expanded #157

__Extensibility__
The order card is one area that also is flagged for extensibility - the Print Menu. We should be able to leverage our prior explorations in the try branches to see the best way for extensions to add actions to the print menu.

**Comment by rrennick** [comment]
This one is all complete except for a couple items covered under separate issues. Closing.
