### ISSUE TITLE
Activity Panel: Inbox

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#176]
**Designs**: [inVision Project](https://automattic.invisionapp.com/d/main#/projects/prototypes/14671248)
**Master Thread**: [link](https://wp.me/p6riRB-3hZ)

![image](https://user-images.githubusercontent.com/22080/42400882-17456a96-8128-11e8-904e-beb81fe82dc9.png)

This issue will serve as a parent issue for all related components and features of the Inbox Activity Panel. When all child tasks are complete, and the issue is closed, we should be able to consider this part of the activity panel _feature complete_ for the initial release of the plugin.

__Components__
The following components ( [designs here](https://automattic.invisionapp.com/d/main#/console/14671248/305077000/preview) ) need to be created ( or updated ) to match the hi fi designs:

- [x] Secondary Button #145
- [x] Card

__States__
- [x] Loading: Mobile / Non #155 ( Shared with Order Panel )
- [x] Unread #177
- [ ] Read #178
- [ ] Actioned #187

__Backend__
- [x] Database notices and actions tables setup and CRUD classes PR #464
- [x] Notices REST API (read, update only at this time) PR #507 
- [x] Notices Redux PR #513 
- [x] Add core customizer notice ("Looking for the Customizer")
- [x] Add core sales record notice #566 
- [x] Add subscription expiring soon and expired notices #693 
- [x] Write docs on how to extend for 3rd party devs #753 
- [x] Notices REST API Tests PR #851
- [x] Bump expiring notices at various intervals - PR #853
- [x] Filter out updates and errors from the inbox - PR #893
- [ ] Notices Read/Unread State
- [ ] Update Inbox unread items badge periodically
- [ ] Update actioned / un-actioned state and track #727 
- [ ] Loading older items in the inbox

**Comment by rrennick** [comment]
This one looks like it's all been completed. If there are any outstanding items they can be added as new issues.
