### ISSUE TITLE
RTL issues

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-admin#1776]
### Date picker
* [x] Custom date picker is broken (#1810).
![image](https://user-images.githubusercontent.com/3616980/54112813-4bd0eb00-43e7-11e9-9c58-2aae5ac8c673.png)
* [x] Date picker is misaligned (#1803).
![image](https://user-images.githubusercontent.com/3616980/54285225-db21fe00-45a1-11e9-8ccf-5a4feccc8a75.png)
* [x] Dot of active option is rendered on top of text (#1781).
![image](https://user-images.githubusercontent.com/3616980/54112842-61461500-43e7-11e9-84c8-116da85548f2.png)

### Ellipsis menu
* [x] Multi-line elements are left-aligned, but they should be aligned to the right (#1781).
![image](https://user-images.githubusercontent.com/3616980/54112920-8175d400-43e7-11e9-891d-d8060994694f.png)
* [x] Ellipsis menu title should be aligned to the right (#1781).
![image](https://user-images.githubusercontent.com/3616980/54112671-fbf22400-43e6-11e9-9124-5a1fec946ff9.png)

### Chart
* [x] Missing spacing between legend label and value (#1781).
![image](https://user-images.githubusercontent.com/3616980/54112476-88e8ad80-43e6-11e9-8412-cddc9b85bf71.png)
* [x] Missing spacing between elements in chart tooltip (#1781).
![image](https://user-images.githubusercontent.com/3616980/54112579-c816fe80-43e6-11e9-90e9-9c222c13d34c.png)
* [x] Y-axis labels should be on the right side of the chart (#1794).
![image](https://user-images.githubusercontent.com/3616980/54112614-e11faf80-43e6-11e9-8156-67bb4b7e5e07.png)
* [x] In left column of _Dashboard_ charts, tooltip is rendered outside of the screen space (#1794).
![image](https://user-images.githubusercontent.com/3616980/54113026-acf8be80-43e7-11e9-8481-d796015b9a29.png)
* [x] Loading spinner circles are misaligned (https://github.com/WordPress/gutenberg/pull/14418).
![circles](https://user-images.githubusercontent.com/3616980/54285467-4cfa4780-45a2-11e9-8cc8-70157a4358d1.gif)

### Table
* [x] Missing margin between _Download_ button icon and text (#1781).
![image](https://user-images.githubusercontent.com/3616980/54112339-3ad3aa00-43e6-11e9-9776-f8a9044950a0.png)
* [x] Missing margin in right align column headers (#1781).
![image](https://user-images.githubusercontent.com/3616980/54112416-6787c180-43e6-11e9-84a0-9bf91150b1dc.png)
* [x] Missing spacing between summary numbers and labels (#1781).
![image](https://user-images.githubusercontent.com/3616980/54112449-779fa100-43e6-11e9-80f4-c6e25a4e21d2.png)

### Filters
* [x] Missing space between report filter dropdowns (#1781).
![image](https://user-images.githubusercontent.com/3616980/54113541-d2d29300-43e8-11e9-99c5-e81473d64aed.png)
* [x] No space between _Filter_ button and _Clear all_ (#1781).
![image](https://user-images.githubusercontent.com/3616980/54113462-a159c780-43e8-11e9-8fa6-8e4236272830.png)
* [x] Missing padding inside search input (#1781).
![image](https://user-images.githubusercontent.com/3616980/54112374-4cb54d00-43e6-11e9-89d9-33ab8de73fd6.png)
* [x] Multi-line suggestions are left-aligned (#1781).
![image](https://user-images.githubusercontent.com/3616980/54113140-f6e1a480-43e7-11e9-8b5a-efba31c91db4.png)
* [x] No space between suggestion icon and name (#1781).
![image](https://user-images.githubusercontent.com/3616980/54113168-052fc080-43e8-11e9-871e-6c00ed575e8a.png)
