### ISSUE TITLE
Add historical data import endpoint

### ISSUE THREAD

**Issue by jeffstieler** [woocommerce/woocommerce-admin#1850]
![Screen Shot 2019-03-19 at 4 57 23 PM](https://user-images.githubusercontent.com/63922/54647441-17ed6980-4a68-11e9-9029-645a92e43f9c.png)

The historical data import tool (above) requires endpoints for the following functionality:

_(It's probably best to split these items into separate PRs)_

- [ ] Updating the Customer and Order counts when a backfill date is chosen or "skip previously imported" is toggled
- [x] Initiating a historical data import #2034 
  * Params: # of days to backfill, whether to skip existing customers/orders
  * Persist the parameters for use in `WC_Admin_Reports_Sync` queries
- [ ] Querying the status of a historical data import
  * Status of current import if in progress - importing customers, importing orders
  * Date of oldest Order imported (used to show how much data has been imported)
- [x] Cancelling an in-process historical data import #2048
- [x] Deleting all previously imported data #2057 

See: p6riRB-3ZT-p2

**Comment by joshuatf** [comment]
>Status of current import if in progress - importing customers, importing orders

@jeffstieler It's technically possible to run 2 imports simultaneously, right?  Do you think we should provide stats on all running imports or try and limit to one import at a time?

/cc @LevinMedia

**Comment by jeffstieler** [comment]
> It's technically possible to run 2 imports simultaneously, right? Do you think we should provide stats on all running imports or try and limit to one import at a time?

I suppose that would be technically possible, but I don't think we want to allow/support that. My vote is to limit to one import at a time.

**Comment by joshuatf** [comment]
>I suppose that would be technically possible, but I don't think we want to allow/support that. My vote is to limit to one import at a time.

I think that's probably the best solution as well.

>Updating the Customer and Order counts when a backfill date is chosen or "skip previously imported" is toggled

These are in reference to the import status, right?  Should we be adding these to the status response or do you think there's benefit added by separating these into a different response?

>Date of oldest Order imported (used to show how much data has been imported)

What were your thoughts on the latest import date?  I don't think we can safely determine number of imports from this since they could skip over a period of imports, but maybe you have something else in mind for this date.

/cc @jeffstieler

**Comment by jeffstieler** [comment]
> > Updating the Customer and Order counts when a backfill date is chosen or "skip previously imported" is toggled
> 
> These are in reference to the import status, right? Should we be adding these to the status response or do you think there's benefit added by separating these into a different response?

Yes this relative to the import. The idea here is that the backfill date and "skip" toggle will affect the query for the data set and therefore the counts displayed in the import UI.

> > Date of oldest Order imported (used to show how much data has been imported)
> 
> What were your thoughts on the latest import date? I don't think we can safely determine number of imports from this since they could skip over a period of imports, but maybe you have something else in mind for this date.

I believe this date should be relative to the current/recently finished import. It's meant to be plugged in to this page in the designs:

<img width="779" alt="Screen Shot 2019-04-19 at 11 51 12 AM" src="https://user-images.githubusercontent.com/63922/56419121-8147de80-6299-11e9-9dd3-0dca4adcc7d5.png">
