### ISSUE TITLE
Add Historical Data Import Screen

### ISSUE THREAD

**Issue by jeffstieler** [woocommerce/woocommerce-admin#1851]
Add an "Import Historical Data" section to the Analytics > Settings page.

UI if historical import tool hasn't been run:

![Screen Shot 2019-03-19 at 4 57 23 PM](https://user-images.githubusercontent.com/63922/54647441-17ed6980-4a68-11e9-9029-645a92e43f9c.png)

Makes use of endpoints created in https://github.com/woocommerce/woocommerce-admin/issues/1850.

Values for dropdown:
* All
* Last 365 days
* Last 90 days
* Last 30 days
* Last 7 days
* Last 24 hours
* Custom

![Screen Shot 2019-03-19 at 5 15 07 PM](https://user-images.githubusercontent.com/63922/54648093-93501a80-4a6a-11e9-9cd5-ef6716e8e3c8.png)

"Custom" invokes a date picker. The value passed to API requests should be the number of days from the chosen date to the current date.

UI when an import is in process:

![Screen Shot 2019-03-19 at 5 16 57 PM](https://user-images.githubusercontent.com/63922/54648256-2721e680-4a6b-11e9-95dc-249cb193b7dd.png)

UI after historical tool has been run:

![Screen Shot 2019-03-19 at 5 21 08 PM with delete](https://user-images.githubusercontent.com/63922/54648913-a7e1e200-4a6d-11e9-9fa5-982b0b84adf3.png)

# Tasks
* [x] Create UI (#2073).
* [x] Hook up actions to endpoints (#2177).
* [ ] Read totals from endpoint (#2208).
* [ ] Read import status endpoint.

**Comment by LevinMedia** [comment]
Prototype for reference: 

https://www.figma.com/proto/G1xF07y9TuuhfirzYtqmIvTO/Analytics-Settings?node-id=140%3A0&viewport=-2633%2C1126%2C0.399093&scaling=min-zoom

**Comment by Aljullu** [comment]
@LevinMedia I noticed there are two different designs for stopping an ongoing import (slides 4 and 8):

![image](https://user-images.githubusercontent.com/3616980/56233973-93046880-6084-11e9-89b3-cd7f3055e2ee.png)
![image](https://user-images.githubusercontent.com/3616980/56233986-9d266700-6084-11e9-845f-ecb800c7924e.png)

One has a button with label _Stop_ and a description text next to it and the other only has a button with the label _Stop Import_. Is that in purpose? In that case, it's not clear to me when we should display one or the other.

**Comment by LevinMedia** [comment]
Opps! My bad, lets use "Stop Import" in all cases.

**Comment by timmyc** [comment]
related: https://wordpress.org/support/topic/is-rebuild-reports-data-possible-with-wp-cli/

Would also be nice to have the option to trigger these jobs via WP CLI

**Comment by alexminza** [comment]
Is it possible to force the Historical Data import if the admin notification does not appear anymore?

A previous version of the plugin was installed before but disabled due to incompatibilities. After installing the new version there is no option to import the historical data.
