### ISSUE TITLE
Onboarding - Task List: Add Products Flow

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#1901]
Depends on #1899, #1900. This issue involves implementing the add products task which contains three different scenarios. See the design thread for implementation details. This issue may be addressed in multiple PRs.

- [ ] Profiler completed, extension required, > 10 products
- [ ] Profiler completed, no extension required, < 10 products
- [ ] Profiler skipped, selling on another platform

As part of this issue, we will also need to modify parts of the interface to lead us back to the dashboard.

- [ ] Return to dashboard from importer
- [ ] Return to dashboard from add new product
- [ ] Collaborate with Alpha/WooCommerce.com to see if they can lead back to the dashboard.

[Designs](https://wp.me/p6riRB-45C) | [Flow Chart](https://wp.me/p6riRB-42m)
