### ISSUE TITLE
Activity Panel: Reviews

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#199]
**Designs**: [inVision](https://automattic.invisionapp.com/share/9RMY8JIJAVG#/screens), [Panel](https://automattic.invisionapp.com/d/main#/console/14616980/303950761/preview)
**Master Thread**: [link](https://teamxthings.wordpress.com/2018/06/21/master-thread-activity-panel/)

<img width="512" alt="screen shot 2018-07-13 at 12 18 05 pm" src="https://user-images.githubusercontent.com/689165/42702218-d7363ce0-8696-11e8-804c-2f0e87ed7fb2.png">

This issue will serve as a parent issue for all related components and features of the Reviews Activity Panel. When all child tasks are complete, and the issue is closed, we should be able to consider this part of the activity panel feature complete for the initial release of the plugin.

__Components__
The following components ( [designs here](https://automattic.invisionapp.com/share/9RMY8JIJAVG#/screens/305602743) ) need to be created ( or updated ) to match the hi fi designs:

- [x] Secondary Split Button #200
- [x] Editor #201
- [x] Product Thumbnail #202
- [x] Review Summary #204
- [x] Primary Button #145
- [x] Borderless Button #145 
- [x] Popover Mobile Styling #151

__States__

- [x] Loading: Mobile / Non #155 ( Shared with Order Panel )
- [x] Collapsed: Mobile / Non #205
- [x] Replying: Mobile / Non #206

**Comment by psealock** [comment]
The final issue of this is closed. Depending on usage, we may open more issues for replying/approving/spam.
