### ISSUE TITLE
Dashboard Customization

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#2009]
This issue will act as the parent issue for all items that pertain to making the Dashboard Experience fully customizable on a per-user basis. The team discussed a number of ideas around how far the customization options should go for the first release, and settled on the following. But first I think it would be good to establish a set of common terminology that is used when describing the features/child issues for this project.

#### Dashboard Sections

![sections](https://user-images.githubusercontent.com/22080/55595880-c6490e00-56fa-11e9-80e0-0a8df284c265.png)

Dashboard _Sections_ are denoted by an instance of a `<SectionHeader />` component which describes what the section is about, and has a combination of section-wide options ( i.e. chart type, and time unit on charts ) and an `<EllipsisMenu />` to select which items to show in the section.

For the first release, sections will only be allowed to contain one type of block - so adding a new section, users will be prompted to choose from the type of blocks ( see below )

#### Dashboard Blocks

Blocks ( not to be confused with editor blocks ) are what can be placed inside of a _Section_. There are currently three types of blocks supported:

**Summary Numbers**
![summary-numbers](https://user-images.githubusercontent.com/22080/55596079-b7169000-56fb-11e9-91b6-d4a4a125c297.png)

**Leaderboards**
![leaderboards2](https://user-images.githubusercontent.com/22080/55596097-cdbce700-56fb-11e9-81a6-a214c425e4ee.png)

**Charts**
![chart-blocks-and-controls](https://user-images.githubusercontent.com/22080/55596099-d4e3f500-56fb-11e9-8aaf-15428104b2e2.png)

#### Dashboard Filters

Currently the only filter provided that controls the data shown within each block is a dashboard-wide Date Range picker. There are no plans at this time to support additional dashboard-wide filters.

### Dashboard Defaults

WooCommerce Admin should ship with a set of default Sections + Block combinations.

- [x] Create Default Sections & Blocks #2040

### Customization Options

Users should be able to add, edit, move, and delete _Sections_ within their dashboard.

- [x] Child Issue to Add a new section. Need Designs / Use Gutenberg (+) pattern. Pick type of Section ( Summary Number, Charts, Leaderboards )
- [x] Child Issue to Edit existing section, rename section title. Need Designs. #2120
- [x] Child Issue to Allow moving sections up and down, akin to moving blocks via arrows in Gutenberg. Needs Designs. No drag and drop support. #2121
- [x] Child Issue to delete a section. Need Design. #2122

### Tasks

- [x] Create feature flag for new "development" version of the dashboard. The current static dashboard is what will be published in the plugin until this parent issue is complete. #2041
- [x] Child Issue: Use defaults dashboard sections/block's determined above to populate the new dashboard
- [x] Child Issue: Create any additional utility methods needed in the data layer to accommodate persisting dashboard modifications to user meta ( not certain if any are needed )
- [ ] Child Issue: REST-API driven chart selections that can be filtered https://github.com/woocommerce/woocommerce-admin/issues/2244

**Comment by psealock** [comment]
@timmyc Can you clarify this last task:

>Child Issue: REST-API driven chart selections that can be filtered

Does this mean filtered Dashboard Charts such as "Orders today with Coupon Code DISCOUNT_123"? In other words, similar to how you can save a metric in Scorecard?

If so, I can create a new issue for that and close this one out.

**Comment by timmyc** [comment]
Hey @psealock sorry that bit wasn't very detailed. Unpacking it a bit here:

So currently the chart options shown in the Ellipsis menu in the charts section is powered by [this config](https://github.com/woocommerce/woocommerce-admin/blob/master/client/dashboard/dashboard-charts/config.js) which in-turn pulls from individual report configs like [this one for orders](https://github.com/woocommerce/woocommerce-admin/blob/master/client/analytics/report/orders/config.js#L14-L39).

Looking back the charts config we started making after the playa meetup with the longer-term goal of this config being powered by the REST API, to allow for extension developers to expose/register their own chart types - akin to what has been built for leaderboards, and performance indicators.

So really I think that issue could go quite deep depending on how far we want to take it - like pulling in the chart settings on each report page via the REST API ( long-term this sounds like a grand idea for extensibility ), but for the dashboard thinking some similar PRs to:

https://github.com/woocommerce/woocommerce-admin/pull/1995

https://github.com/woocommerce/woocommerce-admin/pull/2004

**Comment by psealock** [comment]
Thanks @timmyc for the clarification. I created a new Issue for REST-API driven chart selections, https://github.com/woocommerce/woocommerce-admin/issues/2244.

I will close this one out and leave the remaining issue in the backlog.
