### ISSUE TITLE
Internet Explorer 11 Compatibility 

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce-admin#243]
Per https://browsehappy.com/ and https://github.com/WordPress/gutenberg/blob/master/packages/browserslist-config/index.js, it's suggested we should support IE11.

Unfortunately, there are a number of issues already present in the app. We can use this as a master issue, but we'll probably uncover more and want to handle these in separate issues/PRs.

---

- [x] ActivityPanel tabs missing GridIcons and right padding (#345)

![activitypanel_tabs](https://user-images.githubusercontent.com/689165/43332878-78d9f748-9197-11e8-8b46-b5c3c40da72e.png)

---

- [ ] CSS Grid Usage
  - [x] Card Layout (#370)
  - [ ] Activity Panel
  - [x] Summary Numbers (#353)
  - [x] Date Picker (#366)
  - [ ] Segmented Control

IE11 only supports grid through prefixed properties. `autoprefixer` has a polyfill, but it is not a magic solution. You have to structure your grids a specific way and avoid using some properties. We have the grid capability disabled for now because our rules don't seem to work properly with the `-ms-` prefixes.

Without Grid Mode Enabled:

![gridwithout](https://user-images.githubusercontent.com/689165/43333257-226135f6-9198-11e8-921b-c9b4f4d236ed.png)

With Grid Mode Enabled:

![gridwith](https://user-images.githubusercontent.com/689165/43333598-b16d7cc8-9198-11e8-9f91-65f8e986d2ef.png)

Some resources I found:
* https://github.com/postcss/autoprefixer#faq
* https://css-tricks.com/css-grid-in-ie-css-grid-and-the-new-autoprefixer/

Another option here is to use Grid in newer browsers and something else for older browsers (maybe `display: table-cell`, etc)

---

- [x] Use of CSS variables (gutter padding doesn't work) (#372)

---

- [ ] D3 Chart Size Issues

![d3chart](https://user-images.githubusercontent.com/689165/43333645-dd355024-9198-11e8-86ec-00e21e036aea.png)

---

- [x] Date Picker (Custom Tab) doesn't work, JavaScript Errors (#356)

When attempting to use the custom date picker, a JS error is thrown in IE11 due to `Object.assign` usage:

![image](https://user-images.githubusercontent.com/22080/45173112-16d7a780-b1bc-11e8-9bd2-c1631a09a99c.png)

---

- [x] Date overlaps product name in _Reviews_. (#400)

![image](https://user-images.githubusercontent.com/3616980/45486323-f62ec500-b75a-11e8-875b-358c64b4db28.png)

---

- [x] Only one date is shown in _Custom_ filter. (#411)

**Comment by psealock** [comment]
Can this be closed?

**Comment by Aljullu** [comment]
@psealock I think so, we are tracking new IE11 bugs as independent issues now, so if any of the glitches above is still valid, I think it makes sense creating a new issue for it.
