### ISSUE TITLE
Activity Panel: Stock

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#245]
**Designs**: [inVision](https://automattic.invisionapp.com/d/main#/projects/prototypes/14698454)
**Master Thread**: [link](https://teamxthings.wordpress.com/2018/06/21/master-thread-activity-panel/)

![image](https://user-images.githubusercontent.com/22080/43349850-ae491646-91b7-11e8-92cf-0e6a01f6c145.png)

This issue will serve as a parent issue for all related components and features of the Stock Activity Panel. When all child tasks are complete, and the issue is closed, we should be able to consider this part of the activity panel feature complete for the initial release of the plugin.

__Components__
The following components ( [designs here](https://automattic.invisionapp.com/d/main#/console/14698454/305632622/preview) ) need to be created ( or updated ) to match the hi fi designs:

- [x] Product Thumbnail #202
- [x] Primary Button #145
- [x] Borderless Button #145 

__States__

- [x] Loading: Mobile / Non #155 
- [ ] Collapsed: Mobile / Non #246 
- [ ] Updating Inventory: Mobile / Non #247
