### ISSUE TITLE
e2e Testing: Set up Puppeteer master issue

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#2497]
End to end (e2e) testing automates user flows of navigating apps by simulating clicks and selections.

Add Puppeteer infrastructure and tests so that we can check that reports, pages, and filtering are functioning as they should.

Why Puppeteer? Core will eventually migrate in that direction (p7bje6-1ne-p2).

### Tasks 

- [x] Implement initial Puppeteer architecture #4343
- [x] Write a simple test to test Puppeteer config #4343
- [x] Integrate [Gutenberg’s WP util functions package](https://github.com/WordPress/gutenberg/tree/master/packages/e2e-test-utils)  #4343
- [x] Write documentation on e2e test suite config #4343
- [ ] Create baseline tests for each report and page. Ensure elements are loading correctly.
- [ ] Set up Testing in different browsers
- [x] Integrate with Travis CI #4343
- [ ] Integrate with Slack/email/(something else?) to deliver a notice with screenshot of failed test
- [ ] Identify and create tests for complex flows, ie filtering or settings manipulation.

**Comment by samueljseay** [comment]
This is looking pretty stale now. I think we've done the most important work listed here on e2e for now at least. Some of the leftover tasks could be something we raise later if the value is high enough, but its worth noting that puppeteer only supports FF outside of Chrome sadly.
