### ISSUE TITLE
Onboarding - Task List: List completed

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#2685]
**User Story**
As a new merchant
I want to be able to remove the task list after complete it
So I can focus on other tasks related to my store

**Acceptance Criteria**
- [ ] When the merchant completes the list he can see a message that allows him to hide or keep the list
- [ ] If the merchant chooses to keep the list, he can delete the list by clicking in the top right corner of the list component
- [ ] If the merchant is using the new WC Admin, when he removes the List he stays in the WC Dashboard
- [ ] If the merchant is using the current WC Admin, when he removes the List he is redirected to the Orders area
- [ ] The `wcadmin_tasklist_completed` track event is fired (see the events spreadsheet for event props)

**Links**
[Figma mockup](https://www.figma.com/file/xyKPRZ73kKhDyNjwbFvBJR/Task-List?node-id=999%3A1033)
