### ISSUE TITLE
Data Stores: Expose SQL query objects to extensions

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#2714]
Data stores build objects containing clauses of SQL queries before using them to create complete queries for fetching data. By hooking into these objects via filters, we can allow extension developers to modify queries.

For example, here is the Orders Data Store creating two objects `$totals_query` and `$intervals_query` for the summary numbers and chart, respectively. 

https://github.com/woocommerce/woocommerce-admin/blob/9fbee2b13cac2d73e538bcfba967e198b5d9933b/includes/data-stores/class-wc-admin-reports-orders-stats-data-store.php#L237-L238

### Data Stores
- [ ] #2819 /Notes/DataStore.php	
- [ ] #2882 /API/Reports/Categories/DataStore.php
- [ ] #2883 /API/Reports/Coupons/DataStore.php
- [ ] #2884 /API/Reports/Coupons/Stats/DataStore.php
- [ ] #2885 /API/Reports/Customers/DataStore.php
- [ ] #2886 /API/Reports/Customers/Stats/DataStore.php
- [ ] #2891 /API/Reports/DataStore.php
- [ ] #2892 /API/Reports/Downloads/DataStore.php
- [ ] ~~/API/Reports/Downloads/Stats/DataStore.php~~
- [ ] ~~/API/Reports/Orders/DataStore.php~~
- [ ] ~~/API/Reports/Orders/Stats/DataStore.php~~
- [ ] ~~/API/Reports/Products/DataStore.php~~
- [ ] ~~/API/Reports/Products/Stats/DataStore.php~~
- [ ] ~~/API/Reports/Stock/Stats/DataStore.php~~
- [ ] #2894 /API/Reports/Taxes/DataStore.php
- [ ] #2895 /API/Reports/Taxes/Stats/DataStore.php
- [ ] #2896 /API/Reports/Variations/DataStore.php

### Documentation
- [ ] ~~Example extension, depending if https://github.com/woocommerce/woocommerce-admin/issues/1964 is also ready~~
