### ISSUE TITLE
Tracking Issue: Refactoring for settings changes

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-admin#2943]
This is a followup to #2917.   This issue can be used to track the refactors needed to fully implement the changes introduced by #2917.

* [ ] Utilize the new `AssetDataRegistry` api for registering data to use instead of the filters.
* [x] implement `getSetting` and `setSetting` in all javascript side code. (#3002, #3001)
* [ ] review settings that are boolean type values using strings (i.e. 'yes'/'no' instead of true/false) and modify (see https://github.com/woocommerce/woocommerce-admin/pull/2917#discussion_r326619430)
* [ ] Use SVG for images (see https://github.com/woocommerce/woocommerce-admin/pull/2917#discussion_r326620522)

**Comment by timmyc** [comment]
Doing a bit of clean up and wasn't certain if there was still anything actionable here, so am going to close out.
