### ISSUE TITLE
Analytics: CSV Download

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce-admin#311]
![68747470733a2f2f6175746f6d61747469632e696e766973696f6e6170702e636f6d2f7374617469632d7369676e65642f6c6976652d656d6265642f3236363e280a6-2018-08-07-11-28-25](https://user-images.githubusercontent.com/22080/44428576-a426c500-a549-11e8-9447-cfe97f9b8b34.png)

Background: p90Yrv-LB-p2

The background thread above contains some excellent discussion on this feature from both a business side, and a technical approach. But I did want to highlight this comment from @warrendholmes which sums up the feature nicely:

> we will move forward with functionality to implement exporting all the data.

This issue will act as a parent issue for child tasks related to the Download CSV functionality.

**Phase 1: Browser-Side Export of data in table**
Since the ability to fully export _all_ data that could be returned by a particular set of filters will require some additional server side work, we would like to implement an interim solution so we can conduct usability tests against the Revenue Report ( and others ) prior to the completion of the back-end logic.

As such, phase one will implement the same approach that exists in both Calypso Stats and legacy WooCommerce reports, where data that is already present in the client will be exported. [Calypso CSV Download](https://github.com/Automattic/wp-calypso/tree/a70587157b33783ba4d5e0e4a1e136680d459d51/client/my-sites/stats/stats-download-csv) is one implementation that can be used as prior art.

- [x] Tracking phase one in #312.

**Phase 2: Server Side Job / Endpoints**
As outlined in the background post, the long-term desired setup for the CSV Download involves the creation of a new API endpoint that will accept arguments of report type ( i.e. Revenue Report ), and any associated filters ( i.e. date ranges, unit/day/week/month ) and enqueue a job to query and persist the data as a csv file. An additional endpoint will allow the client-side logic to query and determine the status of a pending export job, and get the download URL for the file when it is complete.

Prior discussion hinted at possibly being able to leverage Woo's built in digital download support to secure the data file export process.

__Server Tasks__
- [x] Implement Job logic to query large data sets, and save results to the file system
- [x] Create API endpoints to allow queueing a new job, and requesting status of prior jobs
- [x] Implement logic to ensure the serving of the exported data files is secure, and files may only be retrieved by store users with proper permissions
 
__Client Side Tasks__
- [ ] Add new logic to the download CSV button to enqueue an export job if the data set in the report table view exceeds the current default page size. That is, if all data is shown in the current view - continue to use the client-side download built during phase one - otherwise leverage the new server job logic.
- [ ] Implement the download via email link

**Comment by jeffstieler** [comment]
Looks like we forgot to clean this one up.

**Comment by psealock** [comment]
@dreiris We were leaning towards going ahead with the UI on this, if I remember correctly. Any final decision?
