### ISSUE TITLE
Add WCPay to the Setup Checklist Payments Task

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-admin#3930]
In order to be able to introduce it in WC 4.1 as the recommended payment option in the new setup checklist payment task.

For all child tasks here, lets use a feature branch of `add/wc-pay` and target all child PRs off of that feature branch.

__Background__
pbIJXs-2c-p2

__Child Issues__
- [ ] `#516` from wcpay for proper redirect back to task list dashboard
- [x] Create Feature Flag #3946 
- [x] Add wcpay to payments checklist #3948

**Comment by pmcpinto** [comment]
Can we close this issue?

**Comment by allendav** [comment]
Yup!
