### ISSUE TITLE
Onboarding Task List changes - home screen

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4096]
**User story:**
As a new merchant
I want to access the setup tasks alongside other information
So I can explore different areas while keeping in mind that I can easily find the store setup tasks

![store-setup](https://user-images.githubusercontent.com/22080/79793161-f6af1a80-8304-11ea-916f-6f10eccedfaf.png)

**Description:** our hypothesis is that we can increase the likelihood of task completion if we display it alongside useful information in the inbox panel. At the same time, we also want to make some small adjustments to the current task list: include a progress bar, an estimated time for each task and an easy way to access again the profiler info. 

**Acceptance criteria:**
- [ ] When the user finishes the store profiler he will be redirected to the home screen where he will see the task list, the inbox panel and the stats overview.
- [ ] We're going to have a new task for the Store profiler. If the user finishes the profiler it will be marked as completed. If the user doesn't finish or skips the profiler entirely it will be shown as incomplete.
- [ ] Each task will display estimated time for completion (see the mockup to get the time for each task)
- [ ] If the user wants to skip the task list, he can do it through an option in the ellipsis menu
- [ ] If the user completes the task list we close the task list and display the quick links (store management) card
- [ ] When the user skips the task list we'll display the quick links (store management) card
- [ ] We'll display a progress bar on the top of the task list that should be updated every time a user completes a task (nice to have)
- [ ] Remove the setup checklist from being displayed on the Analytics home screen - if the new Home screen feature is enabled.

**Event tracking:**
We already have all the event tracking covered, as long as all the events in the existing task list are covered in this change.

**Additional links:**
P2 with final design: pbIJXs-4Z-p2
Designs: https://www.figma.com/file/Z2PiNnkhjrUIiR7IrfJRnU/Home-Screen?node-id=970%3A0

**Comment by jeffstieler** [comment]
@jameskoster 

The current task list shows in full width at the top of the Analytics Dashboard. When you click into a task, the screen becomes dedicated to the task (see screenshots):

![Screen Shot 2020-04-29 at 1 56 48 PM](https://user-images.githubusercontent.com/63922/80641172-b006a200-8a21-11ea-9440-53d50ea94f0e.png)

Task list at the top of the Dashboard.

![Screen Shot 2020-04-29 at 1 57 00 PM](https://user-images.githubusercontent.com/63922/80641214-bd239100-8a21-11ea-8e0a-97d3825b0ac9.png)

Current task is the only thing shown.

So - for the task list display in the new home screen, should the behavior be the same? A big difference is the half width display of the task list jumping to full width..

**Comment by jameskoster** [comment]
Yeah the behaviour should be the same - users are sent to a separate screen.

If changing the width of the layout on task screens is trivial then we should do that, but if not it's not the end of the world to leave it as it is.

**Comment by jeffstieler** [comment]
@jameskoster should the "welcome modal" display on the new home screen?

<img width="1104" alt="Screen Shot 2020-05-12 at 11 14 47 AM" src="https://user-images.githubusercontent.com/63922/81724585-d96ff680-9441-11ea-9744-d68d27d8b5d4.png">

**Comment by jeffstieler** [comment]
What should these step titles become?

1. "Purchase & install extensions"
2. "Connect your store to WooCommerce.com"

**Comment by jameskoster** [comment]
> @jameskoster should the "welcome modal" display on the new home screen?

Good question, do you think we still need this @pmcpinto? I'm not sure how useful it is.

> What should these step titles become and what are their time estimates?

I think the names are fine. Maybe 2 minutes for purchase and install, and 1 minute for the connection task. What do you think? :D

**Comment by pmcpinto** [comment]
> Good question, do you think we still need this @pmcpinto? I'm not sure how useful it is.

I'd keep the modal. It can give a good motivational boost.
