### ISSUE TITLE
Task List - include dismiss button on Purchase Extension and Store Profiler tasks

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4576]
**User story:**
As a new merchant
I want to easily dismiss nonessential tasks
So I can focus on the most important ones

**Description:** we're going to test including a dismiss button in nonessential tasks, such as the Store Profiler and Purchasing Extensions

![dismiss-1.gif](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/f3b05d61-da65-42da-aed0-fcf516633796)

**Acceptance Criteria:**
- [ ] Include a dismiss button in the Store Profiler and Purchase extension task
- [ ] Remove the task if the user clicks "Dismiss"
- [ ] Display a snackbar informing that the task was dismissed and that includes an undo button as well

**Event tracking:**
Event name: `wcadmin_tasklist_dismiss_task`
Event prop: `task_name` (value: task name)
Event description: When the user clicks to dismiss the Store Profiler or the Purchase extension task

**Additional links:**
[Checklist item component](https://www.figma.com/file/Pfw5Qa1UOw03RiJere3Wlo/Automattic-Components?node-id=4533%3A712)

**Comment by becdetat** [comment]
Seems straightforward, wrinkle may be managing options for the tasks being dismissed.

Estimate: 3

**Comment by joshuatf** [comment]
>wrinkle may be managing options for the tasks being dismissed.

Agreed.  Maybe a single option that houses an array of dismissed options, like `woocommerce_task_list_dismissed_tasks`?

**Comment by jeffstieler** [comment]
> we're going to **test** including a dismiss button

Is this meant to be a split test?

> Estimate: 3

Agree with @becdetat 's estimate of 3.. this would take me some time with the animations. Speaking of - could we create a reusable component to facilitate the "slide and fade" dismissal transition? That could be used for the inbox notes as well, and maybe even handle RTL.

**Comment by mattsherman** [comment]
I'd give this a 3 just because of the animations... I've always found them a bit tricky to implement in React, though it's been a long time since I've done anything animation-related, so maybe things are easier now.

**Comment by octaedro** [comment]
I agree with @becdetat. Also, I think that @jeffstieler's plan to have a _reusable component to facilitate the "slide and fade"_ is great.
Probably it was included in the initial estimation, but just because nobody mentioned it, I'll do it: if we want to follow the [same pattern used on the inbox panel](https://cldup.com/kZ6UJZKkF7.gif), we should add to the design an empty placeholder that will appear after pressing `undo` in the `snackbar` to undo the dismiss action. If we want to have this functionality we should additionally add some kind of control watching for the request state (when loading) and replace the placeholder with the undismissed task.
If we want to add this functionality and it wasn't in the initial estimation, it will need to be added.
