### ISSUE TITLE
Task List: Personalize Purchase Extension task

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4578]
**Description:** we want to contextualize the label on the Purchase Extension task, if the merchant selected to purchase a single extension

![screenshot-2020-06-02-at-12.34.18.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/a414c7f8-77c2-41f9-bcfc-4ce30a915de1)

**Acceptance Criteria:**
- [ ] Display the extension name if the user selected one extension: Purchase and install [extension_name] extension
- [ ] Apply the same for themes: Purchase and install [theme_name] theme
- [ ] Keep the task description generic if the user selected more than one product

**Event tracking:**
It won't be necessary additional tracking

**Comment by becdetat** [comment]
Estimate: 1
