### ISSUE TITLE
Task List - provide access to support documentation during the store setup

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4593]
**User story:**
As a new merchant
I want to have access to documentation while I'm completing the store setup
So I can have more context about each task and make the right decisions during the setup 

**Description:** the qualitative survey about the new onboarding experience showed that users need more guidance/help during the store setup. Here we can have the same approach that we're having on #4592 and add a new item to the wcadmin top bar. In this case, it would be exclusive to the store setup tasks pages. 
As a starting point, we can just link out to a single documentation page on docs.woocommerce.com. A nice to have for this first version could be displaying relevant links for each task, but omit the search input and the buttons to open a support ticket or start a live chat.

![support.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/e4c87e72-e7f6-4bea-af89-aece29c192b4)

**Acceptance Criteria:**
- [x] Add a new Help item to the top bar when the setup task list is active. This item should only be available in the setup tasks pages
- [ ] When the user clicks on the Help item, it should be redirected to a different page, depending on the task where he's at:
Add products: https://docs.woocommerce.com/document/managing-products/?utm_source=help_panel
Set up payments: https://docs.woocommerce.com/document/premium-payment-gateway-extensions/?utm_source=help_panel
Set up tax:  https://docs.woocommerce.com/document/setting-up-taxes-in-woocommerce/?utm_source=help_panel
Set up shipping: https://docs.woocommerce.com/documentation/plugins/woocommerce/getting-started/shipping/?utm_source=help_panel
Personalize store: https://docs.woocommerce.com/document/woocommerce-blocks/?utm_source=help_panel

Nice to have
- [x] Reuse the panel pattern employed by the other tabs in the activity panel, to display more than one document on each task:

**Add Products task**
[Adding and Managing Products](https://docs.woocommerce.com/document/managing-products/?utm_source=help_panel)
[Import products using the CSV Importer and Exporter](https://docs.woocommerce.com/document/product-csv-importer-exporter/?utm_source=help_panel)
[Migrate products using Cart2Cart](https://woocommerce.com/products/cart2cart/?utm_source=help_panel)
[Learn more about setting up products](https://docs.woocommerce.com/documentation/plugins/woocommerce/getting-started/setup-products/?utm_source=help_panel)

**Personalize store task**
[Showcase your products and tailor your shopping experience using Blocks](https://docs.woocommerce.com/document/woocommerce-blocks/?utm_source=help_panel)
[Manage Store Notice, Catalog View and Product Images](https://docs.woocommerce.com/document/woocommerce-customizer/?utm_source=help_panel)
[How to choose and change a theme](https://docs.woocommerce.com/document/choose-change-theme/?utm_source=help_panel)

**Set up shipping task**
[Setting up Shipping Zones](https://docs.woocommerce.com/document/setting-up-shipping-zones/?utm_source=help_panel)
[Core Shipping Options](https://docs.woocommerce.com/documentation/plugins/woocommerce/getting-started/shipping/core-shipping-options/?utm_source=help_panel)
[Product Shipping Classes](https://docs.woocommerce.com/document/product-shipping-classes/?utm_source=help_panel)
[WooCommerce Shipping setup and configuration](https://docs.woocommerce.com/document/woocommerce-services/#section-3/?utm_source=help_panel) (if WCS is active)
[Learn more about configuring your shipping settings](https://docs.woocommerce.com/documentation/plugins/woocommerce/getting-started/shipping/?utm_source=help_panel)

**Set up taxes task**
[Setting up Taxes in WooCommerce](https://docs.woocommerce.com/document/setting-up-taxes-in-woocommerce/?utm_source=help_panel)
[Automated Tax calculation using WooCommerce Services](https://docs.woocommerce.com/document/woocommerce-services/?utm_source=help_panel#section-10) (if WCS is active)

**Set up payments task**
[Which Payment Option is Right for Me?](https://docs.woocommerce.com/document/premium-payment-gateway-extensions/?utm_source=help_panel)
[WooCommerce Payments Start Up Guide](https://docs.woocommerce.com/document/payments//?utm_source=help_panel) (if option)
[WooCommerce Payments FAQs](https://docs.woocommerce.com/documentation/woocommerce-payments/woocommerce-payments-faqs/?utm_source=help_panel) (if option)
[Stripe Setup and Configuration ](https://docs.woocommerce.com/document/stripe/?utm_source=help_panel)(if option)
[PayPal Checkout Setup and Configuration](https://docs.woocommerce.com/document/paypal-express-checkout/?utm_source=help_panel) (if option)
[Square - Get started](https://docs.woocommerce.com/document/woocommerce-square/?utm_source=help_panel) (if option)
[Klarna - Introduction](https://docs.woocommerce.com/document/klarna-payments/?utm_source=help_panel) (if option)
[PayFast Setup and Configuration](https://docs.woocommerce.com/document/payfast-payment-gateway/?utm_source=help_panel) (if option)
[Direct Bank Transfer (BACS)](https://docs.woocommerce.com/document/bacs/?utm_source=help_panel)
[Cash on Delivery](https://docs.woocommerce.com/document/cash-on-delivery/?utm_source=help_panel)

**Event tracking:**
We can use the existing wcadmin_activity_panel_open event and add the store setup item as a new value of the tab prop. However, it would be good to have an event prop to identify in which step the user accessed the support doc. This would help us understand which tasks they're having more troubles. So perhaps a new event is the best option here:

Event name: `wcadmin_help_panel_open`
Event prop: `task_name` (value: task name)

Event name: `wcadmin_help_panel_click`
Event prop: `task_name` (value: task name)
Event prop: `link` (value: url)

**Additional links:**
[Design mockup](https://www.figma.com/file/JH9XMFUCOjfXdr3N09AHRD/On-boarding-iterations-June-'20?node-id=48%3A5248)

**Comment by becdetat** [comment]
Estimate: 1
Nice-to-haves estimate: 1

**Comment by timmyc** [comment]
I think I'm going to err on the side of this taking a little bit longer - 2. But will say the pattern here is largely the same as the Quick Links section on the home screen. 

__Alternate Approach__

Given the Help Menu / Panel has been popping up in quite a few of @jameskoster 's designs, I'm thinking we might want to implement something a bit more robust - perhaps a new take on https://codex.wordpress.org/Class_Reference/WP_Screen/add_help_tab, one that could possibly be leveraged in WP core ( Jay do you know of any designs around updating the help tab in the works at all? )

Anyhow here is what I'm thinking:

- Help Panel should be super light/extensible. 
- MVLP would be a render of a simple list of links, akin to the quick links on home screen. Omit the ability to have a search box in the first iteration - instead have a link to the page where one could search support docs on a topic.
- When a user clicks on the help tab, a list of help topics is fetched from a new REST API endpoint
- The REST endpoint would accept a "screen id" as an argument to return contextual help topics
- The REST endpoint response is filterable, this allows for extensions to inject other help topics that pertain to their functionality, for that screen.
- Perhaps an item returned from the REST endpoint would include: icon, text, link. This would allow for this panel to be filled up with not only documentation links, but down the line maybe links to video tutorials and such.
- The Footer element in the support panel.... thinking that might be an interesting target for the REST response too. Maybe just a `_links` portion of the response could return the requisite data needed ( icon, text, target ). Again this allows the panel to be ultra flexible

I'll give this approach an estimate of a 5. I think the REST API logic should be straightforward since it is really READ only. And I think investing a little bit more time up-front on this one will pay off down the road as a really nice way for extensions to add contextual support/help information.

**Comment by jameskoster** [comment]
> the pattern here is largely the same as the Quick Links section on the home screen

Yas! I was hoping we could re-use the quick link component here.

> Jay do you know of any designs around updating the help tab in the works at all?

Nothing on the radar afaik. I wouldn't think that's likely to be a priority for quite some time as the editor environment is still very much the focus.

> Omit the ability to have a search box in the first iteration - instead have a link to the page where one could search support docs on a topic.

One question on that - as an interim solution, instead of bringing the search results in to the slide-out panel dynamically, would it be possible to pass the search terms to docs.woocommerce.com on submit as a query string for the search feature there? So you'd type your search, press enter, and a new tab opens on our docs site:

![search](https://cldup.com/6F5BUnKBXZ.gif)

If that's not possible, then good idea :D We could add two static links:

![image](https://cldup.com/uf4aqqolwr-3000x3000.png)

By adding the search icon link we can at least validate how important documentation searching is in this feature.

**Comment by mattsherman** [comment]
Clicking a documentation link will open up a new browser tab, right?

I'd estimate 2 for a MVP with static links.

5 for a REST API-driven approach for results.

I'd definitely go MVP first, with tracking in place, so we can measure how often this is used before we take the time to implement an API to improve this.

I'd also push to include the live chat and support ticket buttons in the MVP, as those seem quite valuable to new customers, who might not know how to easily figure out how to contact support.

**Comment by pmcpinto** [comment]
> I'd definitely go MVP first, with tracking in place, so we can measure how often this is used before we take the time to implement an API to improve this.

Yep, going with static links seems to be the best option. It's worth keeping in mind that if we display a set of links, in some steps this needs to be dynamic, depending on what we display there:
Payments step: payment providers displayed
Shipping: WCS, JP and Shipstation
Taxes: WCS, JP and Automated Taxes

I'll compile the group of links that we should share on each step.

> I'd also push to include the live chat and support ticket buttons in the MVP, as those seem quite valuable to new customers, who might not know how to easily figure out how to contact support.

On the Woo side, there's an effort to avoid non-paid users to open tickets with simple questions. In order to simplify the logic on Core and the eComm plan, I'd display just one button with a different link for each:

Need additional help?
WC Core: https://woocommerce.com/contact-us/
eComm: https://wordpress.com/help/contact

**Comment by pmcpinto** [comment]
Just a heads up that I updated the issue description with the links that we should display on each task, if we end up implementing the slide panel

**Comment by jeffstieler** [comment]
@pmcpinto - for the tax and shipping steps - the comment says "if WCS active"..

![Screen Shot 2020-07-08 at 10 26 56 AM](https://user-images.githubusercontent.com/63922/86930989-96f72d00-c105-11ea-9f1e-64dd465e1e05.png)

While implementing, this feels perhaps a bit strange. WCS is being shown as a step, but there is no help that mentions it, because it isn't actually installed.

Should we change the logic to be closer to "if WCS is shown in the tasks"?

**Comment by pmcpinto** [comment]
> Should we change the logic to be closer to "if WCS is shown in the tasks"?

Yep, that makes more sense 😄  Thanks for the suggestion!
