### ISSUE TITLE
Task List - highlight WCPay

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#4597]
**Description:** we want to explore a different approach to display WCPay in the task list for users that install it before arriving at the home screen (this should happen if we implement this #4579). Let’s assume a user opts in to installing WC Pay. In the task list we could show this user a “Set up WooCommerce Payments” task instead of the current “Set up Payments” task. In parallel, we'd deliver an inbox Notification highlighting other payment options, including existing partners. If the user didn’t install WC Pay during the Profiler, they would see the existing “Set up payments” task.

![screenshot-2020-06-03-at-19.16.39.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/c3977c9e-daf7-4301-b969-89fcca546d94)

**Acceptance Criteria:**
- [ ] If the user has WCPay installed when he arrives at the home screen/task list for the first time, hide the "Set up payments" task and display a "Set up WooCommerce Payments" task. If the user doesn't have WCPay installed, he'll see the "Set up payments" task.
- [ ] When the user clicks on "Set up WooCommerce Payments task" he'll be automatically redirected to the WC Pay set up flow.
- [ ] Trigger the following inbox notification if the "Set up WooCommerce Payments" task is displayed:
**Title:** Set up additional payment providers
**Content:** Set up additional payment providers, using third-party services or other methods.
**Segmentation:** only users that have the "Set up WooCommerce Payments" task
**Timing:** when the user visits the home screen/task list for the first time
**Cadence:** once
**CTA leads to:** /wp-admin/admin.php?page=wc-admin&task=payments
**CTA label:** Set up payments

**Event tracking:**
Perhaps we can take advantage of the existing events on the task list and just add a new value to the task_name prop: wcpay

Events:
wcadmin_task_view
wcadmin_tasklist_task_completed
wcadmin_tasklist_click

**Additional links:**
[Design mockup](https://www.figma.com/file/JH9XMFUCOjfXdr3N09AHRD/On-boarding-iterations-June-'20?node-id=111%3A483)

**Comment by becdetat** [comment]
Estimate: 2

**Comment by timmyc** [comment]
I think Bec's estimate is a good one for this as it is outlined here.

Alternate idea though: Should we refactor the setup checklist steps to be more extensible? Seems like having the steps be filterable would be a great first step ( and allow for ease of customization in the ecommerce plan ). We could even consider implementing a slot fill for the setup checklist too.

Either approach would open the door for extension developers ( internal and external ) to build upon the setup checklist concept. The more we tightly couple extension-specific logic into our code in wc-admin, the more brittle it will be.

**Comment by joshuatf** [comment]
>Should we refactor the setup checklist steps to be more extensible? Seems like having the steps be filterable would be a great first step

I think the setup checklist is extensible through the `woocommerce_admin_onboarding_task_list` filter, but I agree that any additions, like slot fill, to extensibility we can add there are a win.

>The more we tightly couple extension-specific logic into our code in wc-admin, the more brittle it will be.

Strongly agree.  I think we need to be more modular with all of our components and remove extension specific logic where possible (even when those are coming from internal sources).

WC Pay is a good example of this where we've integrated directly into our components in many cases, but I think we need to start making the push towards better extensibility and for that reason I'd estimate closer to 3-5 with extensibility.

Estimate: 3 or 5 depending on extensibility approach.

**Comment by mattsherman** [comment]
I'd go with a 5 to account for the extensibility concerns.

>  Title: Set up additional payment providers

Why would a user want to setup additional payment providers? In addition to answering to me here, we should consider providing that info in the UI as well for our users! :-)

**Comment by pmcpinto** [comment]
> Why would a user want to setup additional payment providers? In addition to answering to me here, we should consider providing that info in the UI as well for our users!

It's pretty common for merchants to offer more than one provider and it's a requirement of some of the partnerships that we have.

**Comment by mattsherman** [comment]
> It's pretty common for merchants to offer more than one provider and it's a requirement of some of the partnerships that we have.

Why, as a merchant, would I want to setup another payment provider if I have already setup WCPay?

**Comment by pmcpinto** [comment]
> Why, as a merchant, would I want to setup another payment provider if I have already setup WCPay?

About 40% of our users have at least two payment providers, that probably are used as the fallback if the main one has problems.
