### ISSUE TITLE
Task List: add products task - introduce templates

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5296]
**User story:**
As a new merchant
I want to start with a pre-filled product
So I can easily understand what are the most important fields according to the type of product that I want to sell

**Description:** product setup/management is one of the biggest areas of confusion for merchants. There’s an opportunity in the Home screen task list to make this easier by providing product templates for different product types. The goal of the product template is to help merchants understand how to add new products to make the process faster for themselves in the future. For this reason, it feels like there would be more chance of success if we test first with one industry. Otherwise, there’s the chance that starting with a template could actually cost merchants more time if they need to delete a lot of data and start over. We already have sample content for fashion stores and `Fashion, apparel, and accessories` is our biggest vertical, so in this initial iteration we're only going to target merchants that choose this industry. 

![add-product-templates-1.gif](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/f7e42a8f-1038-4be7-a840-93db0c69bdce)

**Acceptance criteria:**
- [ ] Introduce a `Start with a template` option in the `Add Products` task. This option should only be visible for users that selected `Fashion, apparel, and accessories` as the industry.
- [ ] When the user clicks in this option display a modal with 3 different templates:
Physical product
Digital product
Variable product
- [ ] Import the following products from the [sample data](https://github.com/woocommerce/woocommerce/blob/master/sample-data/sample_products.csv) when the user clicks in one of the templates:
Physical product: id - 46
Digital product: id - 73
Variable product: id - 44
- [ ] Open the edit product page with the product that the user selected

**Event tracking:**
- Include `product_template` as value in the `method` prop of `wcadmin_tasklist_add_product`
- Add two new events:

Event name: `wcadmin_tasklist_product_template_selection`
Event prop: `product_type` (physical | digital | variable)
Event description: triggered when the user clicks go

Event name: `wcadmin_tasklist_product_template_dismiss`
Event prop: NA
Event description: triggered when the user clicks in the X to dismiss the modal

**Comment by jeffstieler** [comment]
I think we should add some descriptive (read: plain language) text to explain what the different product types are. For example:

Physical - tangible items that get delivered to customers
Digital - items that customers download or access through your website (online courses, eBooks, images, printable sewing templates)
Variable - products with several versions that customers can choose from (t-shirt sizes or colors, vinyl record or CD)

**Comment by louwie17** [comment]
@pmcpinto in relation to the template data, we have a couple different options to import the template data as a new draft product. I was wondering if there is a requirement to make use of the `sample-data.csv` vs keeping an individual copy of each template type in a format of our choosing (single csv file ([like this](https://github.com/woocommerce/woocommerce-admin/blob/2fbba013f7177ea0e3c9efae60032671eae545f0/src/API/Reports/Products/Templates/digital_product.csv)), or in a php file).

Could there be templates in the future that aren't part of the `sample-data.csv`? if so individual copy's might make more sense.
The only current alterations I had to make to the sample-data was the `published` param, which is set to be published, and the `sku`, mostly as it already existed in my product list (the sample data).
Let me know if I need to clarify any of this.

**Comment by pmcpinto** [comment]
@louwie17 sorry for the late reply. Using the sample-data.csv is not a requirement. Feel free to use the option that's most convenient for this implementation

**Comment by louwie17** [comment]
Btw @pmcpinto do you have any thoughts on what [Jeff mentioned above](https://github.com/woocommerce/woocommerce-admin/issues/5296#issuecomment-747073473)?
> I think we should add some descriptive (read: plain language) text to explain what the different product types are. For example:

**Comment by pmcpinto** [comment]
> Btw @pmcpinto do you have any thoughts on what Jeff mentioned above?

That's a good point, especially for Variable products. It's better to assume that most people don't know what this means.

@elizaan36 what do you think about adding a short description?

**Comment by elizaan36** [comment]
Yeah, I think it helps a lot - I used the copy Jeff suggested without the examples in parentheses.

![Add products](https://user-images.githubusercontent.com/5121465/103956048-5062a980-510d-11eb-9f60-518f910a3572.png)

Also, I put together a mockup of what we could aim for with the modal layout on mobile.

![Add Product -_ Mobile](https://user-images.githubusercontent.com/5121465/103956204-aafc0580-510d-11eb-89b3-323274144b5c.png)
