### ISSUE TITLE
Store setup task list - purchase flow: copy tweaks

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5315]
**Description:** we want to explore moving away from the term “Install” and replacing it with “Add” where appropriate. It feels easier to accomplish and may be more appealing to new customers.

**Acceptance criteria:**
- [ ] Replace the reference to “Purchase and install” in the task list on the Home screen:
If the user selected just one paid extension/theme we'll show “Add [extension/theme name] to my store”
![Captura de ecrã 2020-10-09, às 11.43.01.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/d333cd43-d9a9-49ef-a633-7de7170dd2d9)
If the user selected more than one paid extension/theme we'll show “Add paid extensions to my store”
![Captura de ecrã 2020-10-09, às 11.45.29.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/73a88952-1ca9-48c7-9fa2-8cdd7d734564)
- [ ] Change the modal title to "Would you like to add the following paid features to your store now?"
- [ ] Change the purchase CTA to "Buy now"

![Captura de ecrã 2020-10-09, às 11.51.25.png](https://images.zenhubusercontent.com/5d84fe8e1201de0001b6ab61/8f43f11b-b192-4177-b948-e9e6fa625e5f)

**Event tracking:**
We already have all the tracking in place
