### ISSUE TITLE
Navigation [1.9] Add usage tracking message

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#5930]
**Description:** as requested by Warren here (pbIJXs-vY-p2#comment-1439), users should only be able to enable new features that are being progressively rolled out if they opted into usage sharing.

**Acceptance criteria:**
- [ ] If the user has usage tracking enabled or if he already has the feature enabled, show the option to enable/disable a new feature as we have now.
- [ ] If the user doesn't have usage tracking enabled, display the following content between the features description and the navigation row:
Gathering usage data allows us to make WooCommerce better — your store will be considered as we evaluate new features, judge the quality of an update, or determine if an improvement makes sense. Read about what usage data is tracked `[here](https://woocommerce.com/usage-tracking)`. Enable usage tracking to test new features. Enable usage tracking (CTA - automatically enables tracking when the user clicks on it)
- [ ] The user can only toggle the navigation checkbox after enabling usage tracking
- [ ] This requirement should only happen when a feature is disabled by default for everyone. Eg: Once the nav is enabled by default for new users we drop this requirement.

**Comment by pmcpinto** [comment]
cc @psealock @elizaan36 (in case you want to fine-tune the ux). Thanks

**Comment by psealock** [comment]
Lets hold off on this until the discussion in pbIJXs-vY#comment-1447 can be answered because there are some things to consider before heading down this route.

**Comment by psealock** [comment]
Given the feedback from pbIJXs-vY#comment-1447, I'm closing this issue.

**Comment by joelclimbsthings** [comment]
Since it sounds like we'll be moving forward with this, can we get a bit more detail in the description? I know we were discussing a couple different flows, and @elizaan36 put together some mocks. Can I get a summary and visuals of the direction we're going @pmcpinto ? Thanks!

**Comment by psealock** [comment]
Implement the following modal

![tracking](https://user-images.githubusercontent.com/1922453/104139096-e8160f80-540d-11eb-8f10-699d93bb5e1d.gif)

More information and copy in pbIJXs-wC#comment-1497

## Deliverables 

* The modal only appears for users that are not opted into usage tracking already
* Prevent users from ticking the box without allowing tracking
* It includes a link to https://href.li/?https://woocommerce.com/usage-tracking/

**Comment by elizaan36** [comment]
Hey, looked at this with @pmcpinto this morning and we have some updated copy for the Settings page and modal:

### Settings
<img width="1553" alt="image" src="https://user-images.githubusercontent.com/5121465/104242550-f3c10080-5424-11eb-98a2-869bb09348be.png">
Page title (also subnav): **Beta features**
Body: Test new features to improve the store management experience. These experiments may become the standard experience in future versions of WooCommerce. [Requires usage tracking](https://woocommerce.com/usage-tracking)

### Modal
For the modal, we want to add a slight tweak at the end to let users know they can opt out of usage tracking at any time.
<img width="1890" alt="image" src="https://user-images.githubusercontent.com/5121465/104242872-63cf8680-5425-11eb-8aef-98b4b9916705.png">
Title: Build a better WooCommerce
Body: Testing new features requires sharing non-sensitive data via [usage tracking](https://woocommerce.com/usage-tracking). Gathering usage data allows us to make WooCommerce better — your store will be considered as we evaluate new features, judge the quality of an update, or determine if an improvement makes sense. No personal data is tracked or stored and you can opt-out at any time.
Checkbox: Enable usage tracking
[Save]

Let me know what you think.
