### ISSUE TITLE
Navigation: 1.9 Roll Out Epic

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce-admin#5942]
Make sure the roll out of WC 5.0 which includes WC Admin 1.9 requirements are met. More information in pbIJXs-qm-p2

## 1.8 Requirements (for context)

* eComm users have Nav turned ON
* eComm users have feature setting toggle available
* Plugin and Core users do not have Nav or feature setting toggle available

## 1.9 Requirements

* 1.8 Requirements plus the following:
* Store on WP.com users have Nav turned ON
* Store on WP.com users have feature setting toggle available
* Feature Plugin users have Navigation turned OFF by default
* Feature Plugin have feature setting toggle available

cc @pmcpinto to confirm the above

## Deliverables

- [x] The `config/plugin.json` will have the `navigation` feature ON
- [x] The `config/core.json` will have the `navigation` feature OFF and feature toggle will be visible only in Plugin and Dev builds https://github.com/woocommerce/woocommerce-admin/issues/6029
- [x] Add Usage tracking message https://github.com/woocommerce/woocommerce-admin/issues/5930

**Comment by pmcpinto** [comment]
@psealock there's just one small change in 1.9:

Feature Plugin users have the feature setting toggle available but the navigation is turned off by default

**Comment by psealock** [comment]
Thanks @pmcpinto, I reflected the change in the original comment

**Comment by psealock** [comment]
All child issues are 🚢 so closing this one out
