### ISSUE TITLE
Task List - Payments - Include Mollie as an option

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6042]
**Description**: we're going to start including Mollie as an option in the Payments task in the following countries: FR, DE, UK, AT, CH, ES, IT, PL, FI, NL and BE. More context here: pbIJXs-wP-p2

Probably the easiest way is to use the same approach that we already have for Klarna. See the acceptance criteria.

**Acceptance criteria:**

- [ ] List Mollie below Stripe, PayPal and Klarna in the following countries: FR, DE, UK, AT, CH, ES, IT, PL, FI, NL and BE
- [ ] The copy should be the following:
Title: Mollie Payments for WooCommerce
Description: Effortless payments by Mollie: Offer global and local payment methods, get onboarded in minutes, and supported in your language.
Logo available [here](https://drive.google.com/drive/folders/1eZugbe8-osy94Q4rigRm4SDrqKDtxi3y)
- [ ] When the user clicks "Set up", automatically install the extension from .org ([link](https://wordpress.org/plugins/mollie-payments-for-woocommerce/)).
- [ ] After completing the install and activation, show a 2nd step similar to what we have for Klarna: https://d.pr/i/6tX84U
Title: Connect your Mollie account
Description: Create a [Mollie account](https://www.mollie.com/dashboard/signup) and finish the configuration in the Mollie settings (link Mollie's settings: /wp-admin/admin.php?page=wc-settings&tab=mollie_settings#mollie-payments-for-woocommerce)

**Comment by joshuatf** [comment]
@pmcpinto should this redirect back to the task list after configuration?

Estimate: 2

**Comment by pmcpinto** [comment]
> @pmcpinto should this redirect back to the task list after configuration?

Ideally yes.

**Comment by samueljseay** [comment]
Please note that when choosing "United Kingdom" as country the country code is "GB". I've adjusted the list of supported countries to be "GB" instead of "UK". 

This was a bug in the Klarna step too, which I'll rectify as part of this.

**Comment by samueljseay** [comment]
@pmcpinto When you say redirect to the task list do you mean on the home screen? all the other tasks like Klarna redirect back to the list of payment providers so this would act differently and it would be extra effort to make it seamlessly transition because right now its setup to redirect to the payment provider list first (I tried a basic redirect and it ends up showing the provider list then there is a short delay for a redirect).

**Comment by pmcpinto** [comment]
> Please note that when choosing "United Kingdom" as country the country code is "GB". I've adjusted the list of supported countries to be "GB" instead of "UK".
> This was a bug in the Klarna step too, which I'll rectify as part of this.

Thanks for spotting this 🙏 

> @pmcpinto When you say redirect to the task list do you mean on the home screen? all the other tasks like Klarna redirect back to the list of payment providers so this would act differently and it would be extra effort to make it seamlessly transition because right now its setup to redirect to the payment provider list first (I tried a basic redirect and it ends up showing the provider list then there is a short delay for a redirect).

It should redirect back to the payments providers list, similar to the other payments flows. Sorry if this wasn't 100% clear.
