### ISSUE TITLE
Private mode - spike

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6380]
**User story:**
As a merchant
I want to easily disable public access to the store front-end
So I can update my store and test the changes before visitors can experience them

**Description:** This epic is focused on the spike to evaluate the challenges and required effort to implement this new feature. This eventually will branch out into different issues as we get more clarity and fine-tune the scope. I'll keep a high-level acceptance criteria as we still need to make some decisions based on effort and design explorations. 

**Acceptance criteria:**
- [ ] Users can easily enable the private mode through the wcadmin navbar, home screen or in the settings area. (perhaps we can use the wp_get_environment_type() function)
- [ ] Users should have a clear visual indicator that they’re managing their store in private mode.
- [ ] Only admin and shop managers have access to the store front-end while the private mode is enabled
- [ ] Regular visitors will see a "maintenance" page when visiting the store front-end.
- [ ] The "maintenance" page will be a standardized page, displaying the store logo and name
- [ ] Regular visitors can access the store front-end through a password or magic link (nice to have)
- [ ] Any activity (orders, products, customers) that happens while the private mode is enabled will be displayed in the orders screen and analytics. This should also include triggering emails.
- [ ] All the data generated while the private mode is active can be deleted when the mode is disabled
- [ ] The private mode is enabled by default for new stores. The only exception are existing sites that installed Woo (this requires more exploration)
- [ ] During the beta phase we'll target 5% of new stores
- [ ] The REST API is accessible while the private mode is enabled
- [ ] Trigger the customer effort score right after the private mode is disabled

**Event tracking:**
TBD

**Additional links:**
TBD

**Comment by pmcpinto** [comment]
@samueljseay @elizaan36 just a heads up I already created this epic for the private mode spike. Next week I'll p2 the PRD/Project Thread.

**Comment by pmcpinto** [comment]
The Dotcom team had several problems implementing the v1 of their coming soon mode:
pbAok1-1cz-p2
p7DVsv-8Ue-p2

It would be good to check during the spike if we're going to have similar roadblocks and how we can address them.
