### ISSUE TITLE
Store profiler: business features step improvements

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#6485]
**Description:** the experiment implemented in #5287 showed positive results. Recap here: pbIJXs-GS-p2. We're going to make some improvements in the flow and start targeting more people.

**Acceptance Criteria ( In order of Priority ):**
- [ ] Remove the flow created in #4579
- [ ] Remove the industry restriction and display this flow if the user selected one of the following countries in the store details: US | BR | FR | ID | GB | DE | VN | CA | PL | MY | AU | NG | GR | BE | PT | DK | SE | JP
- [ ] Include WooCommerce Payments if the user selected one of the following countries: US, AU, CA, GB, IE and NZ
- [ ] If the user installs Jetpack and/or WooCommerce Shipping & Tax, he should be redirected to the Jetpack sign up/log in flow at the end of the profiler. As we have now with the original flow
- [ ] Include Mailpoet in the list for any country within the "Grow your store" section: 
Copy: Level up your email marketing with [Mailpoet](https://www.mailpoet.com/woocommerce-email-marketing/)
wp.org link to download plugin: https://wordpress.org/plugins/mailpoet/
- [ ] Display extensions in the following order:
Mailpoet
Facebook
Google Ads
Mailchimp
Creative Mail
- [ ] Change the Creative Mail copy to: Emails made easy with Creative Mail
- [ ] Exclude the WooCommerce Shipping mention if the user is not in the US
- [ ] Include WooCommerce Tax if the user is in one of the following countries: US | FR | GB | DE | CA | PL | AU | GR | BE | PT | DK | SE
- [ ] The WooCommerce Tax copy should be the following: Get automated sales tax with [WooCommerce Tax](https://woocommerce.com/products/tax/)

**Event tracking:**
Currently we have one event that tracks the activity in the two tabs: `wcadmin_storeprofiler_store_business_features_continue` with just one event we're not able to understand if users are dropping in the business details or free features tab. It would be better to have two separate events:
- We can keep `wcadmin_storeprofiler_store_business_features_continue` to track the activity in the free features tab and keep all the associated event props: `all_extensions_installed`, `install_wcpay`, etc
- Add a new one just for the business details tab. We can call it `wcadmin_storeprofiler_store_business_details_continue_variant`. And this one should include all the props associated with this step: `used_platform`, `revenue`, `product_number`, `already_selling`, `used_platform_name`
Event name: `wcadmin_storeprofiler_store_business_features_link_click`
Event description: When the user clicks on one of the extensions link
Event prop: `extension_name` (value: name of the extension that was clicked)

**Additional links:**
Recap of the initial experiment: pbIJXs-GS-p2.
