### ISSUE TITLE
Publish Storybook, remove old react-docgen docs

### ISSUE THREAD

**Issue by samueljseay** [woocommerce/woocommerce-admin#6938]
Usage of wc-admin components has picked up lately and the cracks are showing in the documentation. This is to track important work to get the documentation fixed, published and remove old methods of documenting components.

**Comment by samueljseay** [comment]
I haven't created issues for other work yet, but some ideas include:

- [ ] Publish the new storybook setup with bundled WP css, include a script to run when releasing packages.
- [ ] Remove bin scripts and code for the existing docs that use react docgen
- [ ] Migrate components to TS and remove react prop types usage (Storybook uses react-docgen-typescript to document props)

**Comment by joelclimbsthings** [comment]
Closing this as all contained issues are closed.
