### ISSUE TITLE
Remove “Grow” extensions from onboarding profiler

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#7312]
### User story

As a merchant,
I so not want to have to select extensions to install during the initial setup,
so that I complete the initial setup quickly and can then install only those extensions I really need.

### Description

In preparation to move the marketing extensions into the onboarding task list, these extensions should be removed from the onboarding profile Business Details step.

<img width="564" alt="Screen Shot 2021-07-08 at 2 55 25 PM" src="https://user-images.githubusercontent.com/10561050/124976459-4c9cda80-dffd-11eb-9405-7095939935c4.png">

Since the task list appears to have multiple extension categories, we may want to go with a more whitelist approach from the extensions retrieved from `/wc-admin/onboarding/free-extensions`.  E.g, only show the "basics" category.

### Acceptance criteria

- [ ] The "grow" extensions should not appear in the Business Details step of the OBW
- [ ] The "Get the basics" header should be removed (keep the items under it though!)

### Tasks

- [ ] Remove the "Grow" extensions from the Business Details step of the OBW
- [ ] Remove the "Get the basics" header

**Comment by joshuatf** [comment]
Estimate: 2

**Comment by pmcpinto** [comment]
Hey @joelclimbsthings we need to make a small change in this issue and keep the Mailpoet promotion in the business features step. Let me know if you have any questions. Thanks.

**Comment by pmcpinto** [comment]
> Hey @joelclimbsthings we need to make a small change in this issue and keep the Mailpoet promotion in the business features step. Let me know if you have any questions. Thanks.

Just to clarify, the goal is to have it in both places: business features step and marketing task
