### ISSUE TITLE
Add task to install recommended marketing extensions

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#7313]
### User story

As a merchant,
I want to be prompted to set up marketing tool as part of my store set up,
so that I am aware of the marketing tools that can help my store be successful.

### Description

A new _Set up marketing tools_ task in the Home Screen's _Get ready to start selling_ task list will be added.

### Design

<img width="694" alt="Screen Shot 2021-07-08 at 3 04 57 PM" src="https://user-images.githubusercontent.com/10561050/124977350-60950c00-dffe-11eb-84fb-68319fc40ae4.png">

More details and design in pbIJXs-Ta-p2

### Acceptance criteria

- [ ] Introduce a new task in the setup checklist called "Set up marketing tools" (the title is tbd) and with the following description: "Add recommended marketing tools to reach new customers and grow your business"
- [ ] This new task should be placed after the tax task and before the personalize store task
- [ ] When the user clicks in the marketing task present a "Recommended marketing extensions card" with the following extensions: Mailpoet, Google Ads, Mailchimp and Creative Mail. Here's the copy of each extension:

Mailpoet
Create and send purchase follow-up emails, newsletters, and promotional campaigns straight from your dashboard.

Google Listings and Ads
Get in front of shoppers and drive traffic so you can grow your business with Smart Shopping Campaigns and free listings.

Mailchimp
Send targeted campaigns, recover abandoned carts and much more with Mailchimp.

Creative Mail
Create on-brand store campaigns, fast email promotions and customer retargeting with Creative Mail.

- [ ] We should display the following copy below the card: The extension will be installed and activated for you when you click "Install".
- [ ] When the user clicks "Install", we should automatically install the extensions from wp.org
https://wordpress.org/plugins/mailpoet/
https://wordpress.org/plugins/google-listings-and-ads/
https://wordpress.org/plugins/mailchimp-for-woocommerce/
https://wordpress.org/plugins/creative-mail-by-constant-contact/

### Tasks

- [ ] Creating a new task shown in the task list
- [ ] Record Tracks event `wcadmin_tasklist_click` with a new value called `marketing` in the `task_name` prop when the task is clicked
- [ ] Record Tracks event `wcadmin_task_view` with a new value called `marketing` in the `task_name` prop when the task page is shown
- [ ] Fetching and displaying categories from the free extensions REST endpoint `/wc-admin/onboarding/free-extensions`
- [ ] Handling installation of fetched plugins on clicking _Install_ and showing a success notice (and handling failure as well)
- [ ] Record Tracks event `wcadmin_tasklist_marketing_install` on extension installation with the following props:
    - `selected_extension` : the name of the extension that was selected to be installed
    - `installed_extensions` : an array showing the extensions that were installed when the user clicked to install one extension (TODO: follow up with Pedro to see what was intended)

**Comment by joshuatf** [comment]
Estimate: 5
