### ISSUE TITLE
Manage activated marketing extensions from the marketing extensions task

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#7315]
### User story

As a merchant,
I want to have a link to manage the installed marketing extensions,
so that I can easily manage them without having to hunt down where I need to go.

### Description

In the marketing extensions task, the installed extensions will contain a "Manage" button that links to the extension's settings screen.

Since there are no common APIs to retrieve this information from, I think we'll need to manually provide the settings paths (e.g., `admin.php?page=mailchimp-woocommerce`).  The best place to do this is probably the WCCOM REST API.

Note that these should be partial paths like the example above that allow the consumer (the store site, not WCCOM) to fully construct the URL.

### Design

<img width="692" alt="Screen Shot 2021-07-08 at 3 10 29 PM" src="https://user-images.githubusercontent.com/10561050/124978531-ea91a480-dfff-11eb-8b7a-aef3d26deb87.png">

### Acceptance criteria

- [ ] The "Manage" CTA must redirect users to their own setup flow or settings page:
Mailpoet: /wp-admin/admin.php?page=mailpoet-woocommerce-setup#/woocommerce
Google: /wp-admin/admin.php?page=wc-admin&path=%2Fgoogle%2Fstart
Mailchimp: /wp-admin/admin.php?page=mailchimp-woocommerce
Creative Mail: wp-admin/admin.php?page=creativemail

### Tasks

- [ ] Add the settings paths to the WCCOM REST API (TODO: link to endpoint)
- [ ] Add a "Manage" button to each installed extension, redirecting users to the appropriate URL
- [ ] Record a Tracks event `wcadmin_tasklist_marketing_manage` when the manage link is clicked, with the following props:
    - `selected_extension` : the name of the extension that was selected
    - `installed_extensions` : an array showing the extensions that were installed when the user clicked to manage one extension

**Comment by mattsherman** [comment]
Closing this issue, as it has been implemented (not sure in which PR, but it is functional in `main`).
