### ISSUE TITLE
Mark marketing extension task complete when at least one recommended extension is activated

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#7316]
### User story

As a merchant,
I want the marketing extension task to be marked as complete when I have at least one recommended extension activated,
so that I know that I have taken care of that part of the store setup.

### Description

The new marketing extension task should be marked complete when one of the supplied marketing extensions is installed and activated.

This seems straightforward, but given that the free extensions are remotely fetched, we'll have to compare those to installed extensions on the client.  We've previously preloaded all this data, but ideally we can avoid doing this going forward.

### Acceptance criteria

- [ ] Mark task as completed when the user activates at least one marketing extension

### Tasks

- [ ] Compare remotely fetched extensions to the installed extensions on the client and mark task complete if there is at least one extension activated
- [ ] Record the Tracks event `wcadmin_tasklist_marketing_install` event to track this (TODO: verify this)

**Comment by joshuatf** [comment]
cc @pmcpinto just to double check, should this task be counted as complete when a plugin is installed or activated?

**Comment by pmcpinto** [comment]
Ideally, we should mark it as complete when the plugin is activated.
