### ISSUE TITLE
Tax task - include Avalara Tax extension

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7442]
**User Story:**
As a new merchant
I want to know which tax extension, WooCommerce Tax or Avalara, is the best fit for my needs
So I can have speed up the store setup without spending much time looking for a solution

**Description:** we’re going to broaden our Tax extensions offering in the store setup flow by including Avalara. This will require some changes in the Tax task. The BizDev team is still finalizing details, but the goal is to release the changes in the December release (WC 6.0). See the design exploration here: p6riRB-6mT-p2#comment-7503

**Acceptance Criteria:** 
- [ ] If the store is located in a country where we should include Avalara and WC Tax, display an option before the stepper with the two options. The list of countries where we should present Avalara is [here](https://docs.google.com/spreadsheets/d/12Kk18wE6Q6HcWhiK90mnL4F6cNH-QspkxU5joaxGye8/edit?usp=sharing). 
- [ ] If the user clicks on the Avalara call to action, redirect the user to Avalara's woocommerce.com product page: https://href.li/?https://woocommerce.com/products/woocommerce-avatax/
- [ ] Proceed to the existing stepper if the user selects WC Tax
    - WC Tax and Jetpack will be installed in the existing stepper, as currently is done; no change to this
- [ ] The "Set up taxes manually" and "I don't charge sales taxes" should remain the same
- [ ] The task completion logic needs to be tweaked to mark the task as complete when the Avalara extension is installed
- [ ] If Avalara is installed, we should redirect users to the extension's settings: /wp-admin/admin.php?page=wc-settings&tab=tax&section=avatax
- [ ] If the store location isn't populated before visiting the Tax task, we show the existing flow without the Avalara promo
- [ ] If the store is located in a country only supported by Avalara, only show the Avalara option
- [ ] If the store is located in a country without Avalara or WC Tax support, show the existing configuration stepper that redirects users to settings: https://d.pr/i/NoMXDW

**Event Tracking:**
- `wcadmin_tasklist_tax_view_options`: fires when we display the step with the options
- `wcadmin_tasklist_tax_select_option`: fires when the user selects one of the options
    - `selected_option`: the option selected by the user

**Screenshots/Flow:**
![screen-shot-2021-10-13-at-3 44 39-pm](https://user-images.githubusercontent.com/3380168/137776948-a687c320-8b96-4f29-9966-e38bfd12d9b0.png)

**Tasks:**

- [ ] Show new screen if both WC Tax and Avalara are available for the store's country
    - [ ] Log `wcadmin_tasklist_tax_view_options` when screen is shown
- [ ] Implement new screen actions
    - [ ] Log `wcadmin_tasklist_tax_select_option` Tracks event when option's action button is selected
    - [ ] Redirect user to Avalara site if they select Avalara
- [ ] Mark task as done if Avalara extension is installed (in addition to any current task completion logic)

**Implementation notes:**

- Current tax task fill is getting large and should be refactored to split up into separate components

**Comment by mattsherman** [comment]
> If the user is located in a country

@pmcpinto Is it really the user we care about, or the store address?

**Comment by mattsherman** [comment]
It is a bit unclear to me exactly how this is supposed to fit with the existing task flow. Does Jetpack and WooCommerce Tax now get installed from this new option screen? /cc @elizaan36 @jarekmorawski  

> The WC Tax CTA should be "Finish set up" if the user has WC Tax installed when he visits the Tax task

Does this take the place of the following current screen?

<img width="1045" alt="Screen Shot 2021-10-18 at 20 15 13" src="https://user-images.githubusercontent.com/2098816/137823506-66160eb3-090e-4521-9ae4-990fbdc7b5a9.png">

> The WC Tax CTA should be "Install for free" if the user doesn't have WC Tax installed when he visits the Tax task

Is this supposed to do the same thing as "Install & enable" on the current screen?

<img width="1045" alt="Screen Shot 2021-10-18 at 20 16 41" src="https://user-images.githubusercontent.com/2098816/137823615-d96a4028-d4f5-459c-be08-04a176f7f280.png">

**Comment by mattsherman** [comment]
> mark the task as complete when the user selects Avalara

@pmcpinto Does just selecting Avalara complete the task, or should we be checking to see if a particular extension is installed?

**Comment by mattsherman** [comment]
@pmcpinto Is this good hard-coded in WCA, or should this be driven by a remote endpoint?

**Comment by elizaan36** [comment]
> Does Jetpack and WooCommerce Tax now get installed from this new option screen? /cc @elizaan36 @jarekmorawski
