### ISSUE TITLE
Store Profiler and Product task - include Subscriptions

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7445]
**User Story:**
As a new merchant
I want to have guidance on how to create subscriptions
So I can start selling this type of product as quickly as possible

**Description:** 
We need to tweak the store profiler and add product task flow, to incorporate the new WCP feature.  See the design exploration here: paJDYF-2ha-p2

**Acceptance Criteria:**
- [ ] The changes outlined below should only apply to stores located in the US (added on Oct 7)
- [ ] Remove the Subscriptions paid extension option from the Product Types step and include the Subscriptions free option
- [ ] If the user selects the Subscriptions free option, display the following message at the bottom of the step:
The following extensions will be added to your site for free: WooCommerce Payments. An account is required to use this feature.
- [ ] Install WooCommerce Payments in the Product Types step, if the user proceeds with the Subscriptions free option selected
- [ ] If the user visits the "Add product" task with WCP installed, include Subscriptions as an option in the product template modal
- [ ] If the user selects the subscriptions template option, redirect him to `post-new.php?post_type=product&subscription_pointers=true`

**Tasks:**

- [ ] Add feature flag
- [ ] Change setup wizard to add free subscription to Product Types step
- [ ] Install WooCommerce Payments if free subscription was selected
- [ ] Create a new CSV file with the subscription data and update template modal in products task to use that

**Event Tracking:**
TBD

**Comment by mattsherman** [comment]
@pmcpinto @elizaan36 Is this work dependent on any other work being done? In other words, do we need to wait until anything else is currently in the product before we make these changes?

**Comment by elizaan36** [comment]
Good question! This is the latest conversation that I've seen: paJDYF-2ha#comment-7839

**Comment by mattsherman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mothra-60df2bf941ae44000ebbda7c/issues/woocommerce/woocommerce-admin/7445?planning-poker) with ZenHub @joshuatf @louwie17 @octaedro @joelclimbsthings @jacob-sewell

**Comment by jarekmorawski** [comment]
Hi there. 👋 The latest designs are available [here](https://www.figma.com/file/jcP4y1b7zYi6PfqX8Q22qr/?node-id=521%3A50575). I'll be happy to answer any questions you might have!

**Comment by pmcpinto** [comment]
> @pmcpinto @elizaan36 Is this work dependent on any other work being done? In other words, do we need to wait until anything else is currently in the product before we make these changes?

The Subscriptions feature implementation in WCPay is underway (paJDYF-2rf-p2) and afaik they aim to have it ready before the WC 5.9 release in November. @thenbrent or @haszari can you confirm this? 
This work can be done in parallel, the main drawback is having to roll back the changes if the WCPay work is not done on time. The 5.9 code freeze is October 14th, so that means the changes need to be implemented by the end of September.

**Comment by pmcpinto** [comment]
> Hi there. 👋 The latest designs are available here. I'll be happy to answer any questions you might have!

@jarekmorawski thanks for sharing the designs. Can you check the acceptance criteria of this issue? Just to make sure I'm not missing anything. Thanks!

**Comment by mattsherman** [comment]
> the main drawback is having to roll back the changes if the WCPay work is not done on time

We will use a feature flag to accommodate this. This way, we won't have to roll back any changes if there is a delay.

**Comment by haszari** [comment]
> The Subscriptions feature implementation in WCPay is underway (paJDYF-2rf-p2) and afaik they aim to have it ready before the WC 5.9 release in November. @thenbrent or @haszari can you confirm this?

Confirming we're aiming to ship stripe billing powered subscriptions features in WCPay 3.2 (code freeze Oct 25). 

> We will use a feature flag to accommodate this. This way, we won't have to roll back any changes if there is a delay.

Great! That gives us flexibility in case it's needed :)

**Comment by mattsherman** [comment]
@octaedro Can you please provide an update for this? Is there anything that @joelclimbsthings, @jacob-sewell, or anybody else could assist with?

**Comment by octaedro** [comment]
Hi @mattsherman ,
I started working on this issue late Wednesday and I had Friday and Monday off. I think, that our estimations were correct and it should take 4 or 5 days, so it should be ready by the end of this week (maybe Thursday).

**Comment by joelclimbsthings** [comment]
Just let me know if I can help with anything in parallel/otherwise @octaedro . I'll focus on task-list issues until then 👍🏻

**Comment by octaedro** [comment]
Hi @pmcpinto  and @elizaan36 

I'm working on this issue now and I have a few questions:

After selecting `Subscriptions`  in the store profiler, the option `Add Subscriptions to my store` appears in the setup tasklist.  Should we remove that task item?

![screenshot-one wordpress test-2021 09 28-15_28_06](https://user-images.githubusercontent.com/1314156/135159903-48f8834b-b353-4081-9014-c734fb37456d.png)


> Install WooCommerce Payments in the Product Types step, if the user proceeds with the Subscriptions free option selected

Should we just install WC-Payments or should it be activated too? After having WC-Payments installed, will it continue being shown in the `Bussines Details` > `Free features` section?


> If the user selects the subscriptions template option, redirect him to `post-new.php?post_type=product&subscription_pointers=true`

Should we create a new subscription product with dummy data like the other product types in the list and after that redirect the user to the mentioned URL? Or is the idea just a clean redirection after pressing `Go`?

![screenshot-one wordpress test-2021 09 28-17_23_38](https://user-images.githubusercontent.com/1314156/135160289-29bc4a5a-be96-4ada-8a7f-8f696123244f.png)

**Comment by pmcpinto** [comment]
> After selecting Subscriptions in the store profiler, the option Add Subscriptions to my store appears in the setup tasklist. Should we remove that task item?

That task should be removed in this use case. It was created just for paid extensions

> Should we just install WC-Payments or should it be activated too?

I think it should be also activated

> After having WC-Payments installed, will it continue being shown in the Bussines Details > Free features section?

My recommendation is to remove it from the free features section if installed, to avoid any edge cases like: what should we do if the user deselects the WCPayments extension in this step

> Should we create a new subscription product with dummy data like the other product types in the list and after that redirect the user to the mentioned URL? Or is the idea just a clean redirection after pressing Go?

I'd keep it simple without any dummy data in this initial release. 

cc @elizaan36 for additional feedback

**Comment by mattsherman** [comment]
@octaedro I moved this to the `In Progress` pipeline. Please remember to do this in the future with stories once you start work on them!

**Comment by mattsherman** [comment]
> For WCPay Subscriptions we're basing the decision on the WCPay account location (not the Woo store profile). Ideally we'd use the same code for this decision in WCAdmin and WCPay subs. FYI @mattsherman @octaedro @james-allan
> 
> Perhaps we can use a feature flag from WCPay directly - effectively delegate the decision for whether to show to WCPay Subs onboarding to the WCPay Subs implementation. Then we can avoid a mismatch of onboarding + wcpay features, and simplify releasing.

At the time of onboarding, WCPay is not yet installed. That is precisely what the onboarding support is doing, when the merchants selected "Subscriptions". It is installing WooCommerce Payments for them.

Since WCPay is not installed, the WCPay account location will not be configured yet either.

**Comment by haszari** [comment]
That's a very good point @mattsherman 😄  🤦 .

Sounds like we'll have the possibility of a mismatch between store location in onboarding and what they end up setting for WCPay, but I'm sure that'll be rare in practice.

**Comment by haszari** [comment]
In that case, perhaps it's best for WCPay Subs to defer to the onboarding profile. If merchant is offered WCPay Subscriptions in onboarding, and they opt-in, we activate our feature flag (a `wp_option`). Thoughts @james-allan ?

**Comment by haszari** [comment]
> So I've got your suggestion right @haszari, you're suggesting we should use the store profiler's inputted store location to determine if the store is eligible so we can install WooCommerce Payments and we use that to enable our feature flag.

Yep - that's right. I hadn't considered the non-onboarding case. For onboarding, if we've offered it and they've opted in, it's simpler to enable Subscriptions even if they don't technically meet our preview criteria (USA WCPay account). 

That seems consistent with our general approach - WCPay Subs is available to anyone if they want it (via the `wp_option`); for US-based merchants, we're enabling it automatically (for preview launch).

**Comment by mattsherman** [comment]
Closing this epic as all work has been completed.
