### ISSUE TITLE
Payments task: update eWAY name to Eway

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7591]
**Description:** just a follow-up on #7359. I completely missed that we also need to update the eWAY name. Sorry!

**Acceptance criteria:**

- [ ] Change the eWAY name to Eway

**Tasks**

- [ ] Update `class-payment-gateway-suggestions.php` file on wccom remote endpoint ([file location](https://github.com/Automattic/woocommerce.com/blob/trunk/plugins/wccom-plugins/payment-gateway-suggestions/includes/class-payment-gateway-suggestions.php#L254))
- [ ] Update wc-admin fallback in `DefaultPaymentGateways.php` file ([file location](https://github.com/woocommerce/woocommerce-admin/blob/2d5de364902d586536b1d6f0222a9d1032c46b97/src/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php#L213))

**Comment by jacob-sewell** [comment]
@pmcpinto Do we also need changes in woocommerce core? Specifically [includes/admin/class-wc-admin-setup-wizard.php:1494](https://github.com/woocommerce/woocommerce/blob/trunk/includes/admin/class-wc-admin-setup-wizard.php#L1494).

**Comment by pmcpinto** [comment]
Yes. That would be great. Thanks!
