### ISSUE TITLE
Payments task: include Square in France [FR]

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7631]
**Description:** Square's launch in France is set for Sep 21 and we need to start including the extension in the payments task for french users.

**Acceptance criteria:**

- [ ] Display Square as an option in the payments task if the user selected France (FR) as the country in the Store Details step and if he selected one of the following options in the Business details step - Currently selling elsewhere?
Yes, in person at physical stores and/or events
Yes, on another platform and in person at physical stores and/or events
- [ ] The payments task update using the remote endpoint should be shipped on Sep 22
- [ ] Ideally, we should ship the wc admin fallback option in WC Admin 2.7/ WC Core 5.8. But it can wait until 2.8/5.9 if it's too late. 

**Tasks**

**Note: Do not merge until Sept 22**

- [ ] Update `class-payment-gateway-suggestions.php` file on wccom remote endpoint ([file location](https://github.com/Automattic/woocommerce.com/blob/trunk/plugins/wccom-plugins/payment-gateway-suggestions/includes/class-payment-gateway-suggestions.php#L265))
- [ ] Update wc-admin fallback in `DefaultPaymentGateways.php` file ([file location](https://github.com/woocommerce/woocommerce-admin/blob/2d5de364902d586536b1d6f0222a9d1032c46b97/src/Features/PaymentGatewaySuggestions/DefaultPaymentGateways.php#L224))

**Comment by becdetat** [comment]
@mattsherman Can Mothra handle this please? Pedro has asked if Ghidorah can do it but they are stretched thin with AFK this sprint.

**Comment by mattsherman** [comment]
@becdetat We will do this

**Comment by mattsherman** [comment]
@jacob-sewell This isn't closed until the wc-admin fallback PR is merged as well.
