### ISSUE TITLE
Task List REST API: remove items that aren't visible

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#7647]
To simplify the consuming components on the frontend, we should consider removing items with `false` values for `is_visible` in the REST API response.

Note that certain items like "dismiss" and "snooze" still need to optimistically update and potentially undo that update, which makes me unsure whether or not we can filter visibility on the REST side.  cc @joelclimbsthings 

If we do filter on the server, we can probably remove some of the logic in the `TaskList` component:

https://github.com/woocommerce/woocommerce-admin/blob/a220b6a0c2b9047728b7b4cc43d667b635a1c986/client/tasks/task-list.tsx#L53-L57

## Tasks

- [ ] Update `is_visible` property to `is_????` (naming is hard)
- [ ] In task list model, add method for `get???Tasks()`
- [ ] In REST API handler, filter out `is_visible === false` items and don't include them in response
- [ ] Update logic in client to not filter by `is_visible` property
