### ISSUE TITLE
Task list REST API and component tests

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#7649]
Unit tests are needed for the all the new task endpoints and components.

**Components**
* [ ] `TaskList`
* [ ] `TaskListItem`
* [ ] `Task`
* [ ] `Tasks`

**Endpoints**
* [ ] `onboarding/tasks`
* [ ] `onboarding/tasks/{id}/dismiss`
* [ ] `onboarding/tasks/{id}/undo_dismiss`
* [ ] `onboarding/tasks/{id}/snooze`
* [ ] `onboarding/tasks/{id}/undo_snooze`
* [ ] `onboarding/tasks/{id}/hide`

**APIs**
* [ ] `TaskList` API class
* [ ] `Task` API class

**Comment by joelclimbsthings** [comment]
Would this be better broken up into 2 or 3 issues, for component/endpoint/API tests?

**Comment by joshuatf** [comment]
@joelclimbsthings I don't think this needs multiple issues, but definitely multiple PRs.

I would break this up into as many PRs as possible (up to 1 PR per above item), but if you find that to be overkill, the endpoints could probably be combined.  Not a hard and fast rule, but PRs over a few hundred lines could probably be broken down.

Feel free to edit the above and add your name next to any you're working on.

**Comment by joelclimbsthings** [comment]
> Feel free to edit the above and add your name next to any you're working on.

Perfect, managing who was working on what is what I was wondering about 👍🏻
