### ISSUE TITLE
Task list UI experiment

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#7659]
### User story
As a new merchant,
I want to have a clear focus on the next task,
So I quickly understand why it's important for completing store setup.

### Description
An experiment to test a horizontal layout and new progress UI for the store setup task list. More details in pbIJXs-XM.

### Acceptance criteria
- [ ] Header card with illustration for each task #7636
- [ ] Summary tasks for each task #7637
- [ ] Single column and mobile #7638
- [ ] Hide task list via ellipses menu #7634
- [ ] Success message upon task list completion #7634
- [ ] Task UI A/B experiment with control and variant
- [ ] A/B experiment with single column and 2 column layout #7635
- [ ] Inbox notes to complete/edit store details #7715 
- [ ] Paid extensions task to extended task list #7716 

### Tasks

**Comment by ilyasfoo** [comment]
Closing this as it's done
