### ISSUE TITLE
Task API for task model and registering tasks

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#7661]
The current task list is a rather lengthy array of items with key value pairs of standardiized properties used for tasks.  We should update this to use a datastore-like model that sanitizes data and adds various helper methods to a `Task`.

The `Task` model should house the following properties/methods:

* `id`
* `title`
* `content`
* `action_label`
* `action_url`
* `is_complete`
* `is_visible` - Note that this is semantically incorrect and may be updated in https://github.com/woocommerce/woocommerce-admin/issues/7647.
* `time`
* `is_dismissable`
* `is_snoozeable`

**Tasks**
* [ ] Create `add_task` method to `TaskList` and store lists in a class instance
* [ ] Add Task model with respective setter and getter methods
* [ ] Migrate current tasks into separate classes and register individually

**Comment by mattsherman** [comment]
@joshuatf Is this ready to be groomed/estimates by @woocommerce/mothra? If so, please move it to the Groom pipeline on the Mothra board and let the team know. Thanks!
