### ISSUE TITLE
Inbox note: Habit moment survey

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-admin#7662]
We’ve identified that updating multiple orders within a short time can indicate a successful store, however we’re not clear on other key habits that are an indication of thriving stores.

**New inbox note, delivered using the remote system:**

**Title:** We're all ears! Share your experience so far with WooCommerce
**Content:** We'd love your input to shape the future of WooCommerce together. Feel free to share any feedback, ideas or suggestions that you have.
**Segmentation:** store_age > 3 months; order_count > 30; product_count > 0
**Timing:** Immediate (no trigger)
**Cadence:** once
**CTA leads to:** https://automattic.survey.fm/store-management
**CTA label:** Share feedback

**Acceptance criteria:**

- [ ] A new inbox note is delivered, using the remote system, with the details shown above
- [ ] The CTA for the note redirects the user to the survey

**Tasks:**

- [ ] Implement new inbox note using the remote system (wccom)

**Comment by pmcpinto** [comment]
I think we should user product_count and order_count:

product_count: > 0
order_count > 3

@becdetat what do you think?

**Comment by becdetat** [comment]
@pmcpinto I would have expected significantly more than three orders over three months as an indication of a thriving store but I'm happy to be wrong. Everything else looks ok :-)

**Comment by pmcpinto** [comment]
Ahah good point. I'd go with 30 orders if we want to only target "successful" stores. @elizaan36 do you think we should include merchants who are struggling or just successful stores?

**Comment by elizaan36** [comment]
Ideally we would target higher volume stores for this one, so the survey itself can do less of the segmentation work. A higher order count would be good and >30 sounds good to me. Will update that and the product count in the description. If there's not enough of a response we can adjust.
