### ISSUE TITLE
Header should allow for items to be slot filled

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce-admin#7689]
### Is your feature request related to a problem? Please describe.
The header area could benefit from SlotFill, allowing new elements to be added.  There's interest in displaying WCCOM connection info in the header, but doing so would require back and forth logic between the WC repo and WCA repo when in reality this logic should probably be housed outside the WCA repo.

See p90Yrv-2u2-p2 for more context.

### Describe the solution you'd like
Add one or more SlotFills to allow the header to be more extensible.

### Describe alternatives you've considered
The alternative is adding code that doesn't belong in WCA or positioning the new element absolutely 😱

### Tasks

- [ ] Add SlotFill(s) to the header where appropriate
- [ ] Possibly migrate existing components to a SlotFill.  `MobileAppBanner` should probably be separated.  `Navigation` and `ActivityPanel` both have feature flags and could benefit from being separated out.
- [ ] Add example extensions with usage

**Comment by joshuatf** [comment]
Closed by https://github.com/woocommerce/woocommerce-admin/pull/7805
