### ISSUE TITLE
Store setup: update WCPay copy to include a mention of in-person payments

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7719]
**Description:** the in-person payments feature is coming soon to WCPayments. The initial release will be limited to COD and US merchants. See this post with more info: pbIJXs-YR-p2
We want to update the copy in the main touchpoints of the WCPayments setup flow, to promote the new feature. 

**Design:**

Welcome screen:

> With WooCommerce Payments, you can securely accept major cards, Apple Pay, and payments in over 100 currencies – with no setup costs or monthly fees – and you can now accept in-person payments with the Woo mobile app. Learn more

<img width="718" alt="image" src="https://user-images.githubusercontent.com/5121465/135379249-02a3571a-197e-43c7-acf6-4583edc3b4d6.png">

Payments task:

> With WooCommerce Payments, you can securely accept major cards, Apple Pay, and payments in over 100 currencies – with no setup costs or monthly fees – and you can now accept in-person payments with the Woo mobile app. Learn more

<img width="694" alt="image" src="https://user-images.githubusercontent.com/5121465/135379574-ae489fdd-c45a-4b60-95f9-bafd9ee68bd0.png">

One other thing - in the current payments task I noticed that the "Finish setup" action on the WCPay card needs to be aligned left with the text above. 

<img width="208" alt="image" src="https://user-images.githubusercontent.com/5121465/135379771-919d8daf-d1a6-4054-bcda-0d1866f7d90f.png">

**Acceptance criteria:**
- [ ] Update the WCPayments banner in the Payments task (woocomerce-admin) with information about in-person payments. This change should only target users located in the US
- [ ] Update the WCPayments welcome screen (woocommerce-payments) with information about in-person payments. This change should only target users located in the US

**Event tracking:**
We don't need to make any event tracking changes

**Tasks:**

- [ ] Update text in Payments task WCPayments banner (fallback) (woocommerce-admin)
- [ ] Update "Finish setup" button alignment in Payments task WCPayments banner (woocommerce-admin)
- [ ] Update remote endpoint in wccom (woocommerce.com)
- [ ] Update text in WCPayments welcome screen (woocommerce-payments) - may have already been done? Check with WCPay 3.2

**Comment by pmcpinto** [comment]
@elizaan36 you can add the copy changes here. Thanks!

**Comment by joshuatf** [comment]
Thanks, @pmcpinto!  Do we have a version we're targeting for this change?

**Comment by elizaan36** [comment]
Here's what I've got for copy.

### Welcome screen
> With WooCommerce Payments, you can securely accept major cards, Apple Pay, and payments in over 100 currencies – with no setup costs or monthly fees – and you can now accept in-person payments with the Woo mobile app. Learn more

<img width="718" alt="image" src="https://user-images.githubusercontent.com/5121465/135379249-02a3571a-197e-43c7-acf6-4583edc3b4d6.png">

### Payments task (It's the same - I don't see any reason to have different copy here, do you @pmcpinto ?)
> With WooCommerce Payments, you can securely accept major cards, Apple Pay, and payments in over 100 currencies – with no setup costs or monthly fees – and you can now accept in-person payments with the Woo mobile app. Learn more

<img width="694" alt="image" src="https://user-images.githubusercontent.com/5121465/135379574-ae489fdd-c45a-4b60-95f9-bafd9ee68bd0.png">

One other thing - in the current payments task I noticed that the "Finish setup" action on the WCPay card needs to be aligned left with the text above. 
<img width="208" alt="image" src="https://user-images.githubusercontent.com/5121465/135379771-919d8daf-d1a6-4054-bcda-0d1866f7d90f.png">

**Comment by pmcpinto** [comment]
> Payments task (It's the same - I don't see any reason to have different copy here, do you @pmcpinto ?)
It makes sense to apply the same copy change there.

> Thanks, @pmcpinto! Do we have a version we're targeting for this change?

AFAIK they plan to release it in mid-November. But let me confirm the exact date.

**Comment by pmcpinto** [comment]
> AFAIK they plan to release it in mid-November. But let me confirm the exact date.

@joshuatf it will be released October 18th. When do you think it will be possible to release the updates?

**Comment by joshuatf** [comment]
Closed by https://github.com/woocommerce/woocommerce-admin/pull/7830
