### ISSUE TITLE
Show/Hide new task list (REST api version)

### ISSUE THREAD

**Issue by louwie17** [woocommerce/woocommerce-admin#7721]
## Description

The task list should be able to be hidden and shown. When hidden this should be reflected right away.

## Todo's

- [x] Allow user to hide the task list without having to refresh the page
- [x] Activity panels (Reviews/Orders/Stock) should show once the task list has been hidden
- [x] Should trigger a `tasklist_completed` track when user hides the list
- [x] List can be re-shown through the Help panel in a none wc homescreen page
