### ISSUE TITLE
OBW: reintroduce Google Listings and Ads extension in the business features step of OBW

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-admin#7780]
**Description:** the drop in the number of users installing the marketing extensions was higher than we expected and the conv. rate improvement in the flow post-installation is not enough to offset the drop in installs. So we aim to reintroduce the prompt to install Google Listings and Ads in the business features step and keep the marketing task to guide users to finish the setup of each extension and allow them to install Mailchimp or Creative Mail, to cover the case when Mailpoet doesn't fulfill the user needs. More info here: p73Jol-1HW-p2#comment-5613

**Acceptance criteria:**

- [ ] In the Business Features step of the OBW, reintroduce the prompt to Google Listing and Ads, below MailPoet.
    - Copy: `Drive sales with [Google Listings and Ads]`
- [ ] Keep the marketing task on the home screen, to guide users to finish the setup of each extension and install Mailchimp and Creative Mail

<img width="522" alt="Screen Shot 2021-10-19 at 14 26 26" src="https://user-images.githubusercontent.com/2098816/137969297-a950296b-8347-496e-bd34-b70fd6ebe143.png">

**Event tracking:** we don't need to make any changes in terms of tracking

**Tasks:**

- [ ] Look up the PR(s) that removed this to see what needs to be added back
- [ ] Make change to remote endpoint (wccom)
    - Do a confidence check to make sure backwards compatibility isn't an issue
- [ ] Make local fallback changes

**Comment by mattsherman** [comment]
> @mattsherman just a heads up that I updated the acceptance criteria, as we only need to reintroduce Google Listing and Ads in the Business Features step. Let me know if you have more news about this:
> 
> > Note: probably can't totally be done by remote endpoint; will require WCA changes as well
> 
> If the blocker is splitting the step into two sections, we can update the list of extensions through the remote endpoint and wait for a wcadmin/core release to implement this split. Thanks!

@joshuatf @joelclimbsthings Would we be able to add Google Listing and Ads back in without a WCA/Core release?
