### ISSUE TITLE
Include WCPayments menu item in WCA

### ISSUE THREAD

**Issue by moon0326** [woocommerce/woocommerce-admin#8062]
**Description:** we want to expand the experiment implemented in [#686](https://github.com/Automattic/wc-calypso-bridge/issues/686) and [#744](https://github.com/automattic/wc-calypso-bridge/issues/744)
More info here: p1634651781002000-slack-C01LPBCV4J1

The code is already done in WC Calypso Bridge repository. We should copy the code from the bridge repository to WCA.

**Acceptance criteria:**

- [ ] Reuse the same flow implemented in https://github.com/automattic/wc-calypso-bridge/issues/744
- [ ] exclude new users and users who already have the extension installed
- [ ] We want to start with a small subset of US stores (% tbd). Using ExPlat seems to be the best approach to segment the two experiences

**Event tracking:** 
It was challenging to find a way to track when the user viewed the menu item. It would be helpful to explore if it's possible to track this in this experiment accurately.
Maybe we can get this through ExPlat without creating new Tracks. We can use an event like `wcadmin_page_view` as the exposure event and then ExPlat automatically shows the variant with the menu item to X number of people 🤔
