### ISSUE TITLE
Task List: Add Products Task - Layout Experiment

### ISSUE THREAD

**Issue by verofasulo** [woocommerce/woocommerce-admin#8406]
**User story:**
As a new merchant
I want to start with a pre-filled product
So I can easily understand what are the most important fields according to the type of product that I want to sell.

**Description:** 
We reviewed the Add products page and built upon the Start with a template idea that performed well in the [previous testing](https://github.com/woocommerce/woocommerce-admin/issues/5296). 

We'd like to try out two different layouts: 

1. **Card layout**: is based on showing multiple cards in a grid.

![Card Layout](https://user-images.githubusercontent.com/98944206/156599140-5fcbdf97-430c-4dc7-80f6-15bf5174b331.gif)

2. **Stack layout**: the product types are vertically stacked. 

![Stack Layout](https://user-images.githubusercontent.com/98944206/156599341-f2b9d0eb-374a-446f-9d30-dcd8a25f052f.gif)

**Design overview:**
[Figma](https://www.figma.com/file/cJQeyyhx9PraQrY3YAtCGM/Setup-Tasks---Flows?node-id=273%3A39990)

**Acceptance criteria:**

- [ ] This page is visible to users that just started their business or skipped the Profiler. If they declared they're already selling somewhere else, they're addressed to a different screen.
- [ ] The visible product types depend on what the user declared during the signup. The other ones are collapsed. (e.g. if the user declared "I want to sell physical products", the visible options would be "Physical product", "Variable Product" and "Grouped products". [More examples here](https://www.figma.com/file/cJQeyyhx9PraQrY3YAtCGM/Setup-Tasks---Flows?node-id=507%3A51023).)
- [ ] Includes the Load sample products feature that allows users to preview what their store might look like. 
- [ ] Includes new icons and new copy.
- [ ] Includes a 1.5 px `Gutenberg-blue` border when components are hovered (instead of grey background).

**Event tracking:** 
To be assessed by the team - some things I'd like to measure:

- Task completion rate
- Task completion time on average (the amount of time it takes a user to select an option and move to the next step).
- % of users that clicks on suggested product types
- % of users that clicks on view more product types
- % of users that clicks on start black VS start with a template
- % of users that follows the suggested pathway (import products or start with a template) VS follow the secondary one
- List of the most clicked product types
