### ISSUE TITLE
Task List: Import products Task 

### ISSUE THREAD

**Issue by verofasulo** [woocommerce/woocommerce-admin#8407]
**User story:**
As a new merchant with an existing product catalog
I want to be able to see the import options highlighted
So I can quickly import my products. 

**Description:** 
We reviewed the Add products page to organize the options according to the user profile. If users declared they're already selling somewhere else, they're addressed to the "Import products" page that makes more prominent options such as "Import from CSV" and "Import from Cart2Cart". All the other options are collapsed, yet still reachable by users.  

![Import Page](https://user-images.githubusercontent.com/98944206/156612070-1d5560dd-4e4e-494b-add7-2d14769efb70.gif)

![image](https://user-images.githubusercontent.com/98944206/156612274-28692672-dfd2-4f2a-88a6-0b7910d492b5.png)

**Design overview:**
[Figma](https://www.figma.com/file/cJQeyyhx9PraQrY3YAtCGM/Setup-Tasks---Flows?node-id=273%3A39990)

**Acceptance criteria:**

- [ ] This page is visible to users that declared to run a business and sell products somewhere else.
- [ ] Includes new icons and new copy.
- [ ] Includes a 1.5 px Gutenberg-blue border when components are hovered (instead of grey background). 
- [ ] Collapse all the other options that are not focused on importing products.

**Event tracking:**
_To be assessed by the team_ - some things I'd like to measure:

- Task completion rate
- Task completion time on average (the amount of time it takes a user to select an option and move to the next step).
- % of users that clicks on one of the two recommended options
- % of users that clicks on "add your products from scratch"
- % of users that clicks on one product type pr start blank
- List of the most clicked import products option (from CSV or Cart2Cart)
